package managementhttp

import (
	"encoding/json"
	"fmt"
	"reflect"
	"slices"
	"strings"
	"time"

	"github.com/juex-ai/juex/internal/calendar"
	"github.com/juex-ai/juex/internal/execution"
	"github.com/juex-ai/juex/internal/foundation/execprotocol"
	"github.com/juex-ai/juex/internal/foundation/llm"
	mc "github.com/juex-ai/juex/internal/foundation/memoryclient"
	"github.com/juex-ai/juex/internal/managedruntime"
	"github.com/juex-ai/juex/internal/management"
	"github.com/juex-ai/juex/internal/memory"
)

// GenerateTypeScript keeps the public JSON response types shared with the Web.
func GenerateTypeScript() ([]byte, error) {
	g := typeGenerator{types: map[string]reflect.Type{}}
	for _, typ := range []reflect.Type{
		reflect.TypeFor[managedruntime.UsageReport](),
		reflect.TypeFor[management.NotificationPage](), reflect.TypeFor[management.NotificationPreferences](), reflect.TypeFor[NotificationReadRequest](),
		reflect.TypeFor[calendar.Status](), reflect.TypeFor[calendar.SchedulePage](), reflect.TypeFor[calendar.OccurrencePage](), reflect.TypeFor[calendar.Receipt](), reflect.TypeFor[CalendarConfiguration](), reflect.TypeFor[CalendarChange](),
		reflect.TypeFor[memory.Status](), reflect.TypeFor[MemoryConfiguration](), reflect.TypeFor[memory.ReviewPage](), reflect.TypeFor[memory.StorageRules](), reflect.TypeFor[mc.Page](), reflect.TypeFor[mc.FactPage](), reflect.TypeFor[mc.AdminRequest](),
		reflect.TypeFor[management.User](), reflect.TypeFor[management.Session](),
		reflect.TypeFor[management.TenantAccess](), reflect.TypeFor[management.MemberView](),
		reflect.TypeFor[management.InvitationView](), reflect.TypeFor[management.InvitationPreview](),
		reflect.TypeFor[management.Fleet](),
		reflect.TypeFor[management.FleetOverview](), reflect.TypeFor[management.Model](),
		reflect.TypeFor[management.AgentDetail](),
		reflect.TypeFor[execution.Device](), reflect.TypeFor[execution.Pairing](),
		reflect.TypeFor[execprotocol.Environment](),
		reflect.TypeFor[execution.Artifact](), reflect.TypeFor[execution.ArtifactUpload](), reflect.TypeFor[execprotocol.FileChunk](),
		reflect.TypeFor[execution.Transfer](), reflect.TypeFor[ExtendTransferRequest](),
		reflect.TypeFor[management.AgentConfig](), reflect.TypeFor[ConfigureAgentRequest](), reflect.TypeFor[ArchiveAgentRequest](),
		reflect.TypeFor[managedruntime.Thread](), reflect.TypeFor[managedruntime.Timeline](), reflect.TypeFor[managedruntime.CompactionRequest](), reflect.TypeFor[managedruntime.InputRequest](), reflect.TypeFor[managedruntime.InputReceipt](), reflect.TypeFor[WorkerRequest](), reflect.TypeFor[ArchiveThreadRequest](), reflect.TypeFor[llm.Message](),
	} {
		if _, err := g.render(typ); err != nil {
			return nil, err
		}
	}
	bodies := map[string]string{}
	for len(bodies) < len(g.types) {
		for name, typ := range g.types {
			if _, exists := bodies[name]; exists {
				continue
			}
			body, err := g.fields(typ)
			if err != nil {
				return nil, err
			}
			bodies[name] = body
		}
	}
	var out strings.Builder
	out.WriteString("// Code generated by go run ./scripts/gen-management-schema. DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "export type Role = %q | %q;\n", management.Admin, management.Member)
	fmt.Fprintf(&out, "export type MembershipStatus = %q | %q | %q;\n\n", management.Active, management.Suspended, management.Removed)
	names := make([]string, 0, len(bodies))
	for name := range bodies {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		fmt.Fprintf(&out, "export interface %s {\n%s}\n\n", name, bodies[name])
	}
	return []byte(strings.TrimRight(out.String(), "\n") + "\n"), nil
}

type typeGenerator struct{ types map[string]reflect.Type }

func (g *typeGenerator) fields(typ reflect.Type) (string, error) {
	var out strings.Builder
	for i := 0; i < typ.NumField(); i++ {
		f := typ.Field(i)
		if !f.IsExported() {
			continue
		}
		tag := strings.Split(f.Tag.Get("json"), ",")
		if tag[0] == "-" {
			continue
		}
		if f.Anonymous && tag[0] == "" {
			body, err := g.fields(f.Type)
			if err != nil {
				return "", err
			}
			out.WriteString(body)
			continue
		}
		if tag[0] == "" {
			return "", fmt.Errorf("missing JSON tag on %s.%s", typ, f.Name)
		}
		kind, err := g.render(f.Type)
		if err != nil {
			return "", err
		}
		optional := ""
		if slices.Contains(tag, "omitempty") {
			optional = "?"
		}
		fmt.Fprintf(&out, "  %s%s: %s;\n", tag[0], optional, kind)
	}
	return out.String(), nil
}

func (g *typeGenerator) render(typ reflect.Type) (string, error) {
	if typ == reflect.TypeFor[[]byte]() {
		return "string", nil
	}
	if typ == reflect.TypeFor[json.RawMessage]() {
		return "unknown", nil
	}
	if typ == reflect.TypeFor[time.Time]() {
		return "string", nil
	}
	if typ == reflect.TypeFor[management.Role]() || typ == reflect.TypeFor[management.MembershipStatus]() {
		return typ.Name(), nil
	}
	switch typ.Kind() {
	case reflect.Interface:
		return "unknown", nil
	case reflect.Pointer:
		inner, err := g.render(typ.Elem())
		return inner + " | null", err
	case reflect.Map:
		if typ.Key().Kind() != reflect.String {
			return "", fmt.Errorf("unsupported JSON map %s", typ)
		}
		inner, err := g.render(typ.Elem())
		return "Record<string, " + inner + ">", err
	case reflect.String:
		return "string", nil
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint64, reflect.Float64:
		return "number", nil
	case reflect.Slice:
		inner, err := g.render(typ.Elem())
		return "Array<" + inner + ">", err
	case reflect.Struct:
		name := typ.Name()
		if typ.PkgPath() == "github.com/juex-ai/juex/internal/memory" || typ.PkgPath() == "github.com/juex-ai/juex/internal/foundation/memoryclient" {
			name = "Memory" + name
		}
		if typ.PkgPath() == "github.com/juex-ai/juex/internal/calendar" || typ.PkgPath() == "github.com/juex-ai/juex/internal/calendar/recurrence" {
			name = "Calendar" + name
		}
		if existing, exists := g.types[name]; exists && existing != typ {
			return "", fmt.Errorf("conflicting JSON type %s", typ)
		}
		g.types[name] = typ
		return name, nil
	default:
		return "", fmt.Errorf("unsupported JSON type %s", typ)
	}
}
