// Code generated by Kitex v0.16.3. DO NOT EDIT.

package calendar

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Purge": kitex.NewMethodInfo(
		purgeHandler,
		newCalendarPurgeArgs,
		newCalendarPurgeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newCalendarHealthArgs,
		newCalendarHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Status": kitex.NewMethodInfo(
		statusHandler,
		newCalendarStatusArgs,
		newCalendarStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Configure": kitex.NewMethodInfo(
		configureHandler,
		newCalendarConfigureArgs,
		newCalendarConfigureResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Schedules": kitex.NewMethodInfo(
		schedulesHandler,
		newCalendarSchedulesArgs,
		newCalendarSchedulesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Occurrences": kitex.NewMethodInfo(
		occurrencesHandler,
		newCalendarOccurrencesArgs,
		newCalendarOccurrencesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Change": kitex.NewMethodInfo(
		changeHandler,
		newCalendarChangeArgs,
		newCalendarChangeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AssignTrigger": kitex.NewMethodInfo(
		assignTriggerHandler,
		newCalendarAssignTriggerArgs,
		newCalendarAssignTriggerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Assignment": kitex.NewMethodInfo(
		assignmentHandler,
		newCalendarAssignmentArgs,
		newCalendarAssignmentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelCommand": kitex.NewMethodInfo(
		cancelCommandHandler,
		newCalendarCancelCommandArgs,
		newCalendarCancelCommandResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	calendarServiceInfo                = NewServiceInfo()
	calendarServiceInfoForClient       = NewServiceInfoForClient()
	calendarServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return calendarServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return calendarServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return calendarServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Calendar"
	handlerType := (*platform.Calendar)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "platform",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func purgeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.CalendarPurgeArgs)
	realResult := result.(*platform.CalendarPurgeResult)
	success, err := handler.(platform.Calendar).Purge(ctx, realArg.RequestJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarPurgeArgs() interface{} {
	return platform.NewCalendarPurgeArgs()
}

func newCalendarPurgeResult() interface{} {
	return platform.NewCalendarPurgeResult()
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*platform.CalendarHealthArgs)
	realResult := result.(*platform.CalendarHealthResult)
	success, err := handler.(platform.Calendar).Health(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarHealthArgs() interface{} {
	return platform.NewCalendarHealthArgs()
}

func newCalendarHealthResult() interface{} {
	return platform.NewCalendarHealthResult()
}

func statusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.CalendarStatusArgs)
	realResult := result.(*platform.CalendarStatusResult)
	success, err := handler.(platform.Calendar).Status(ctx, realArg.AccessJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarStatusArgs() interface{} {
	return platform.NewCalendarStatusArgs()
}

func newCalendarStatusResult() interface{} {
	return platform.NewCalendarStatusResult()
}

func configureHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.CalendarConfigureArgs)
	realResult := result.(*platform.CalendarConfigureResult)
	success, err := handler.(platform.Calendar).Configure(ctx, realArg.AccessJSON, realArg.Version, realArg.Enabled)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarConfigureArgs() interface{} {
	return platform.NewCalendarConfigureArgs()
}

func newCalendarConfigureResult() interface{} {
	return platform.NewCalendarConfigureResult()
}

func schedulesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.CalendarSchedulesArgs)
	realResult := result.(*platform.CalendarSchedulesResult)
	success, err := handler.(platform.Calendar).Schedules(ctx, realArg.AccessJSON, realArg.Offset, realArg.Limit)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarSchedulesArgs() interface{} {
	return platform.NewCalendarSchedulesArgs()
}

func newCalendarSchedulesResult() interface{} {
	return platform.NewCalendarSchedulesResult()
}

func occurrencesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.CalendarOccurrencesArgs)
	realResult := result.(*platform.CalendarOccurrencesResult)
	success, err := handler.(platform.Calendar).Occurrences(ctx, realArg.AccessJSON, realArg.ScheduleID, realArg.Offset, realArg.Limit)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarOccurrencesArgs() interface{} {
	return platform.NewCalendarOccurrencesArgs()
}

func newCalendarOccurrencesResult() interface{} {
	return platform.NewCalendarOccurrencesResult()
}

func changeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.CalendarChangeArgs)
	realResult := result.(*platform.CalendarChangeResult)
	success, err := handler.(platform.Calendar).Change(ctx, realArg.AccessJSON, realArg.ScopeJSON, realArg.CommandID, realArg.ChangeJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarChangeArgs() interface{} {
	return platform.NewCalendarChangeArgs()
}

func newCalendarChangeResult() interface{} {
	return platform.NewCalendarChangeResult()
}

func assignTriggerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.CalendarAssignTriggerArgs)
	realResult := result.(*platform.CalendarAssignTriggerResult)
	success, err := handler.(platform.Calendar).AssignTrigger(ctx, realArg.ScopeJSON, realArg.OccurrenceID, realArg.Epoch)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarAssignTriggerArgs() interface{} {
	return platform.NewCalendarAssignTriggerArgs()
}

func newCalendarAssignTriggerResult() interface{} {
	return platform.NewCalendarAssignTriggerResult()
}

func assignmentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.CalendarAssignmentArgs)
	realResult := result.(*platform.CalendarAssignmentResult)
	success, err := handler.(platform.Calendar).Assignment(ctx, realArg.ScopeJSON, realArg.OccurrenceID, realArg.Epoch)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarAssignmentArgs() interface{} {
	return platform.NewCalendarAssignmentArgs()
}

func newCalendarAssignmentResult() interface{} {
	return platform.NewCalendarAssignmentResult()
}

func cancelCommandHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.CalendarCancelCommandArgs)
	realResult := result.(*platform.CalendarCancelCommandResult)
	success, err := handler.(platform.Calendar).CancelCommand(ctx, realArg.ScopeJSON, realArg.CommandID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalendarCancelCommandArgs() interface{} {
	return platform.NewCalendarCancelCommandArgs()
}

func newCalendarCancelCommandResult() interface{} {
	return platform.NewCalendarCancelCommandResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Purge(ctx context.Context, requestJSON string) (r *platform.Reply, err error) {
	var _args platform.CalendarPurgeArgs
	_args.RequestJSON = requestJSON
	var _result platform.CalendarPurgeResult
	if err = p.c.Call(ctx, "Purge", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context) (r *platform.Reply, err error) {
	var _args platform.CalendarHealthArgs
	var _result platform.CalendarHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Status(ctx context.Context, accessJSON string) (r *platform.Reply, err error) {
	var _args platform.CalendarStatusArgs
	_args.AccessJSON = accessJSON
	var _result platform.CalendarStatusResult
	if err = p.c.Call(ctx, "Status", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Configure(ctx context.Context, accessJSON string, version int64, enabled bool) (r *platform.Reply, err error) {
	var _args platform.CalendarConfigureArgs
	_args.AccessJSON = accessJSON
	_args.Version = version
	_args.Enabled = enabled
	var _result platform.CalendarConfigureResult
	if err = p.c.Call(ctx, "Configure", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Schedules(ctx context.Context, accessJSON string, offset int32, limit int32) (r *platform.Reply, err error) {
	var _args platform.CalendarSchedulesArgs
	_args.AccessJSON = accessJSON
	_args.Offset = offset
	_args.Limit = limit
	var _result platform.CalendarSchedulesResult
	if err = p.c.Call(ctx, "Schedules", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Occurrences(ctx context.Context, accessJSON string, scheduleID string, offset int32, limit int32) (r *platform.Reply, err error) {
	var _args platform.CalendarOccurrencesArgs
	_args.AccessJSON = accessJSON
	_args.ScheduleID = scheduleID
	_args.Offset = offset
	_args.Limit = limit
	var _result platform.CalendarOccurrencesResult
	if err = p.c.Call(ctx, "Occurrences", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Change(ctx context.Context, accessJSON string, scopeJSON string, commandID string, changeJSON string) (r *platform.Reply, err error) {
	var _args platform.CalendarChangeArgs
	_args.AccessJSON = accessJSON
	_args.ScopeJSON = scopeJSON
	_args.CommandID = commandID
	_args.ChangeJSON = changeJSON
	var _result platform.CalendarChangeResult
	if err = p.c.Call(ctx, "Change", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AssignTrigger(ctx context.Context, scopeJSON string, occurrenceID string, epoch int64) (r *platform.Reply, err error) {
	var _args platform.CalendarAssignTriggerArgs
	_args.ScopeJSON = scopeJSON
	_args.OccurrenceID = occurrenceID
	_args.Epoch = epoch
	var _result platform.CalendarAssignTriggerResult
	if err = p.c.Call(ctx, "AssignTrigger", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Assignment(ctx context.Context, scopeJSON string, occurrenceID string, epoch int64) (r *platform.Reply, err error) {
	var _args platform.CalendarAssignmentArgs
	_args.ScopeJSON = scopeJSON
	_args.OccurrenceID = occurrenceID
	_args.Epoch = epoch
	var _result platform.CalendarAssignmentResult
	if err = p.c.Call(ctx, "Assignment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelCommand(ctx context.Context, scopeJSON string, commandID string) (r *platform.Reply, err error) {
	var _args platform.CalendarCancelCommandArgs
	_args.ScopeJSON = scopeJSON
	_args.CommandID = commandID
	var _result platform.CalendarCancelCommandResult
	if err = p.c.Call(ctx, "CancelCommand", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
