// Code generated by Kitex v0.16.3. DO NOT EDIT.

package runtime

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Health(ctx context.Context, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Submit(ctx context.Context, actor *platform.Actor, requestID string, threadID string, text string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Threads(ctx context.Context, actor *platform.Actor, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Timeline(ctx context.Context, actor *platform.Actor, threadID string, after int64, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Cancel(ctx context.Context, actor *platform.Actor, threadID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	CreateWorker(ctx context.Context, actor *platform.Actor, parentID string, requestID string, name string, callOptions ...callopt.Option) (r *platform.Reply, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRuntimeClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRuntimeClient struct {
	*kClient
}

func (p *kRuntimeClient) Health(ctx context.Context, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx)
}

func (p *kRuntimeClient) Submit(ctx context.Context, actor *platform.Actor, requestID string, threadID string, text string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Submit(ctx, actor, requestID, threadID, text)
}

func (p *kRuntimeClient) Threads(ctx context.Context, actor *platform.Actor, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Threads(ctx, actor)
}

func (p *kRuntimeClient) Timeline(ctx context.Context, actor *platform.Actor, threadID string, after int64, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Timeline(ctx, actor, threadID, after, limit)
}

func (p *kRuntimeClient) Cancel(ctx context.Context, actor *platform.Actor, threadID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Cancel(ctx, actor, threadID)
}

func (p *kRuntimeClient) CreateWorker(ctx context.Context, actor *platform.Actor, parentID string, requestID string, name string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateWorker(ctx, actor, parentID, requestID, name)
}
