// Code generated by Kitex v0.16.3. DO NOT EDIT.

package runtime

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AdmitApplication": kitex.NewMethodInfo(
		admitApplicationHandler,
		newRuntimeAdmitApplicationArgs,
		newRuntimeAdmitApplicationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApplicationReceipt": kitex.NewMethodInfo(
		applicationReceiptHandler,
		newRuntimeApplicationReceiptArgs,
		newRuntimeApplicationReceiptResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelApplication": kitex.NewMethodInfo(
		cancelApplicationHandler,
		newRuntimeCancelApplicationArgs,
		newRuntimeCancelApplicationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newRuntimeHealthArgs,
		newRuntimeHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Submit": kitex.NewMethodInfo(
		submitHandler,
		newRuntimeSubmitArgs,
		newRuntimeSubmitResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Threads": kitex.NewMethodInfo(
		threadsHandler,
		newRuntimeThreadsArgs,
		newRuntimeThreadsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Timeline": kitex.NewMethodInfo(
		timelineHandler,
		newRuntimeTimelineArgs,
		newRuntimeTimelineResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Compact": kitex.NewMethodInfo(
		compactHandler,
		newRuntimeCompactArgs,
		newRuntimeCompactResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Archive": kitex.NewMethodInfo(
		archiveHandler,
		newRuntimeArchiveArgs,
		newRuntimeArchiveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Cancel": kitex.NewMethodInfo(
		cancelHandler,
		newRuntimeCancelArgs,
		newRuntimeCancelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateWorker": kitex.NewMethodInfo(
		createWorkerHandler,
		newRuntimeCreateWorkerArgs,
		newRuntimeCreateWorkerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	runtimeServiceInfo                = NewServiceInfo()
	runtimeServiceInfoForClient       = NewServiceInfoForClient()
	runtimeServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return runtimeServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return runtimeServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return runtimeServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Runtime"
	handlerType := (*platform.Runtime)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "platform",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func admitApplicationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeAdmitApplicationArgs)
	realResult := result.(*platform.RuntimeAdmitApplicationResult)
	success, err := handler.(platform.Runtime).AdmitApplication(ctx, realArg.ScopeJSON, realArg.JobJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeAdmitApplicationArgs() interface{} {
	return platform.NewRuntimeAdmitApplicationArgs()
}

func newRuntimeAdmitApplicationResult() interface{} {
	return platform.NewRuntimeAdmitApplicationResult()
}

func applicationReceiptHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeApplicationReceiptArgs)
	realResult := result.(*platform.RuntimeApplicationReceiptResult)
	success, err := handler.(platform.Runtime).ApplicationReceipt(ctx, realArg.ScopeJSON, realArg.Application, realArg.JobID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeApplicationReceiptArgs() interface{} {
	return platform.NewRuntimeApplicationReceiptArgs()
}

func newRuntimeApplicationReceiptResult() interface{} {
	return platform.NewRuntimeApplicationReceiptResult()
}

func cancelApplicationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeCancelApplicationArgs)
	realResult := result.(*platform.RuntimeCancelApplicationResult)
	success, err := handler.(platform.Runtime).CancelApplication(ctx, realArg.ScopeJSON, realArg.Application, realArg.JobID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeCancelApplicationArgs() interface{} {
	return platform.NewRuntimeCancelApplicationArgs()
}

func newRuntimeCancelApplicationResult() interface{} {
	return platform.NewRuntimeCancelApplicationResult()
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*platform.RuntimeHealthArgs)
	realResult := result.(*platform.RuntimeHealthResult)
	success, err := handler.(platform.Runtime).Health(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeHealthArgs() interface{} {
	return platform.NewRuntimeHealthArgs()
}

func newRuntimeHealthResult() interface{} {
	return platform.NewRuntimeHealthResult()
}

func submitHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeSubmitArgs)
	realResult := result.(*platform.RuntimeSubmitResult)
	success, err := handler.(platform.Runtime).Submit(ctx, realArg.Actor, realArg.RequestID, realArg.ThreadID, realArg.Text)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeSubmitArgs() interface{} {
	return platform.NewRuntimeSubmitArgs()
}

func newRuntimeSubmitResult() interface{} {
	return platform.NewRuntimeSubmitResult()
}

func threadsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeThreadsArgs)
	realResult := result.(*platform.RuntimeThreadsResult)
	success, err := handler.(platform.Runtime).Threads(ctx, realArg.Actor)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeThreadsArgs() interface{} {
	return platform.NewRuntimeThreadsArgs()
}

func newRuntimeThreadsResult() interface{} {
	return platform.NewRuntimeThreadsResult()
}

func timelineHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeTimelineArgs)
	realResult := result.(*platform.RuntimeTimelineResult)
	success, err := handler.(platform.Runtime).Timeline(ctx, realArg.Actor, realArg.ThreadID, realArg.After, realArg.Limit)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeTimelineArgs() interface{} {
	return platform.NewRuntimeTimelineArgs()
}

func newRuntimeTimelineResult() interface{} {
	return platform.NewRuntimeTimelineResult()
}

func compactHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeCompactArgs)
	realResult := result.(*platform.RuntimeCompactResult)
	success, err := handler.(platform.Runtime).Compact(ctx, realArg.Actor, realArg.ThreadID, realArg.RequestID, realArg.Focus)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeCompactArgs() interface{} {
	return platform.NewRuntimeCompactArgs()
}

func newRuntimeCompactResult() interface{} {
	return platform.NewRuntimeCompactResult()
}

func archiveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeArchiveArgs)
	realResult := result.(*platform.RuntimeArchiveResult)
	success, err := handler.(platform.Runtime).Archive(ctx, realArg.Actor, realArg.ThreadID, realArg.Archived)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeArchiveArgs() interface{} {
	return platform.NewRuntimeArchiveArgs()
}

func newRuntimeArchiveResult() interface{} {
	return platform.NewRuntimeArchiveResult()
}

func cancelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeCancelArgs)
	realResult := result.(*platform.RuntimeCancelResult)
	success, err := handler.(platform.Runtime).Cancel(ctx, realArg.Actor, realArg.ThreadID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeCancelArgs() interface{} {
	return platform.NewRuntimeCancelArgs()
}

func newRuntimeCancelResult() interface{} {
	return platform.NewRuntimeCancelResult()
}

func createWorkerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.RuntimeCreateWorkerArgs)
	realResult := result.(*platform.RuntimeCreateWorkerResult)
	success, err := handler.(platform.Runtime).CreateWorker(ctx, realArg.Actor, realArg.ParentID, realArg.RequestID, realArg.Name)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRuntimeCreateWorkerArgs() interface{} {
	return platform.NewRuntimeCreateWorkerArgs()
}

func newRuntimeCreateWorkerResult() interface{} {
	return platform.NewRuntimeCreateWorkerResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AdmitApplication(ctx context.Context, scopeJSON string, jobJSON string) (r *platform.Reply, err error) {
	var _args platform.RuntimeAdmitApplicationArgs
	_args.ScopeJSON = scopeJSON
	_args.JobJSON = jobJSON
	var _result platform.RuntimeAdmitApplicationResult
	if err = p.c.Call(ctx, "AdmitApplication", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApplicationReceipt(ctx context.Context, scopeJSON string, application string, jobID string) (r *platform.Reply, err error) {
	var _args platform.RuntimeApplicationReceiptArgs
	_args.ScopeJSON = scopeJSON
	_args.Application = application
	_args.JobID = jobID
	var _result platform.RuntimeApplicationReceiptResult
	if err = p.c.Call(ctx, "ApplicationReceipt", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelApplication(ctx context.Context, scopeJSON string, application string, jobID string) (r *platform.Reply, err error) {
	var _args platform.RuntimeCancelApplicationArgs
	_args.ScopeJSON = scopeJSON
	_args.Application = application
	_args.JobID = jobID
	var _result platform.RuntimeCancelApplicationResult
	if err = p.c.Call(ctx, "CancelApplication", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context) (r *platform.Reply, err error) {
	var _args platform.RuntimeHealthArgs
	var _result platform.RuntimeHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Submit(ctx context.Context, actor *platform.Actor, requestID string, threadID string, text string) (r *platform.Reply, err error) {
	var _args platform.RuntimeSubmitArgs
	_args.Actor = actor
	_args.RequestID = requestID
	_args.ThreadID = threadID
	_args.Text = text
	var _result platform.RuntimeSubmitResult
	if err = p.c.Call(ctx, "Submit", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Threads(ctx context.Context, actor *platform.Actor) (r *platform.Reply, err error) {
	var _args platform.RuntimeThreadsArgs
	_args.Actor = actor
	var _result platform.RuntimeThreadsResult
	if err = p.c.Call(ctx, "Threads", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Timeline(ctx context.Context, actor *platform.Actor, threadID string, after int64, limit int32) (r *platform.Reply, err error) {
	var _args platform.RuntimeTimelineArgs
	_args.Actor = actor
	_args.ThreadID = threadID
	_args.After = after
	_args.Limit = limit
	var _result platform.RuntimeTimelineResult
	if err = p.c.Call(ctx, "Timeline", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Compact(ctx context.Context, actor *platform.Actor, threadID string, requestID string, focus string) (r *platform.Reply, err error) {
	var _args platform.RuntimeCompactArgs
	_args.Actor = actor
	_args.ThreadID = threadID
	_args.RequestID = requestID
	_args.Focus = focus
	var _result platform.RuntimeCompactResult
	if err = p.c.Call(ctx, "Compact", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Archive(ctx context.Context, actor *platform.Actor, threadID string, archived bool) (r *platform.Reply, err error) {
	var _args platform.RuntimeArchiveArgs
	_args.Actor = actor
	_args.ThreadID = threadID
	_args.Archived = archived
	var _result platform.RuntimeArchiveResult
	if err = p.c.Call(ctx, "Archive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Cancel(ctx context.Context, actor *platform.Actor, threadID string) (r *platform.Reply, err error) {
	var _args platform.RuntimeCancelArgs
	_args.Actor = actor
	_args.ThreadID = threadID
	var _result platform.RuntimeCancelResult
	if err = p.c.Call(ctx, "Cancel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateWorker(ctx context.Context, actor *platform.Actor, parentID string, requestID string, name string) (r *platform.Reply, err error) {
	var _args platform.RuntimeCreateWorkerArgs
	_args.Actor = actor
	_args.ParentID = parentID
	_args.RequestID = requestID
	_args.Name = name
	var _result platform.RuntimeCreateWorkerResult
	if err = p.c.Call(ctx, "CreateWorker", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
