// Code generated by Kitex v0.16.3. DO NOT EDIT.

package servicecontrol

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	control "github.com/juex-ai/juex/internal/foundation/serviceendpoint/wire/control"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Inspect(ctx context.Context, expected *control.Identity, callOptions ...callopt.Option) (r *control.Identity, err error)
	Stop(ctx context.Context, expected *control.Identity, callOptions ...callopt.Option) (err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kServiceControlClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kServiceControlClient struct {
	*kClient
}

func (p *kServiceControlClient) Inspect(ctx context.Context, expected *control.Identity, callOptions ...callopt.Option) (r *control.Identity, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Inspect(ctx, expected)
}

func (p *kServiceControlClient) Stop(ctx context.Context, expected *control.Identity, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Stop(ctx, expected)
}
