// Code generated by Kitex v0.16.3. DO NOT EDIT.

package servicecontrol

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	control "github.com/juex-ai/juex/internal/foundation/serviceendpoint/wire/control"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Inspect": kitex.NewMethodInfo(
		inspectHandler,
		newServiceControlInspectArgs,
		newServiceControlInspectResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Stop": kitex.NewMethodInfo(
		stopHandler,
		newServiceControlStopArgs,
		newServiceControlStopResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	serviceControlServiceInfo                = NewServiceInfo()
	serviceControlServiceInfoForClient       = NewServiceInfoForClient()
	serviceControlServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return serviceControlServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return serviceControlServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return serviceControlServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ServiceControl"
	handlerType := (*control.ServiceControl)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "control",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func inspectHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*control.ServiceControlInspectArgs)
	realResult := result.(*control.ServiceControlInspectResult)
	success, err := handler.(control.ServiceControl).Inspect(ctx, realArg.Expected)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServiceControlInspectArgs() interface{} {
	return control.NewServiceControlInspectArgs()
}

func newServiceControlInspectResult() interface{} {
	return control.NewServiceControlInspectResult()
}

func stopHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*control.ServiceControlStopArgs)

	err := handler.(control.ServiceControl).Stop(ctx, realArg.Expected)
	if err != nil {
		return err
	}

	return nil
}
func newServiceControlStopArgs() interface{} {
	return control.NewServiceControlStopArgs()
}

func newServiceControlStopResult() interface{} {
	return control.NewServiceControlStopResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Inspect(ctx context.Context, expected *control.Identity) (r *control.Identity, err error) {
	var _args control.ServiceControlInspectArgs
	_args.Expected = expected
	var _result control.ServiceControlInspectResult
	if err = p.c.Call(ctx, "Inspect", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Stop(ctx context.Context, expected *control.Identity) (err error) {
	var _args control.ServiceControlStopArgs
	_args.Expected = expected
	var _result control.ServiceControlStopResult
	if err = p.c.Call(ctx, "Stop", &_args, &_result); err != nil {
		return
	}
	return nil
}
