// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package memorywire

import (
	"context"
	"fmt"
)

type Call struct {
	FleetID    string `thrift:"fleetID,1,required" frugal:"1,required,string" json:"fleetID"`
	ServiceID  string `thrift:"serviceID,2,required" frugal:"2,required,string" json:"serviceID"`
	InstanceID string `thrift:"instanceID,3,required" frugal:"3,required,string" json:"instanceID"`
	Caller     string `thrift:"caller,4,required" frugal:"4,required,string" json:"caller"`
	Payload    string `thrift:"payload,5,required" frugal:"5,required,string" json:"payload"`
}

func NewCall() *Call {
	return &Call{}
}

func (p *Call) InitDefault() {
}

func (p *Call) GetFleetID() (v string) {
	return p.FleetID
}

func (p *Call) GetServiceID() (v string) {
	return p.ServiceID
}

func (p *Call) GetInstanceID() (v string) {
	return p.InstanceID
}

func (p *Call) GetCaller() (v string) {
	return p.Caller
}

func (p *Call) GetPayload() (v string) {
	return p.Payload
}
func (p *Call) SetFleetID(val string) {
	p.FleetID = val
}
func (p *Call) SetServiceID(val string) {
	p.ServiceID = val
}
func (p *Call) SetInstanceID(val string) {
	p.InstanceID = val
}
func (p *Call) SetCaller(val string) {
	p.Caller = val
}
func (p *Call) SetPayload(val string) {
	p.Payload = val
}

func (p *Call) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Call(%+v)", *p)
}

var fieldIDToName_Call = map[int16]string{
	1: "fleetID",
	2: "serviceID",
	3: "instanceID",
	4: "caller",
	5: "payload",
}

type Memory interface {
	Status(ctx context.Context, request *Call) (r string, err error)

	Search(ctx context.Context, request *Call) (r string, err error)

	Read(ctx context.Context, request *Call) (r string, err error)

	Propose(ctx context.Context, request *Call) (r string, err error)

	Result_(ctx context.Context, request *Call) (r string, err error)

	Claim(ctx context.Context, request *Call) (r string, err error)

	Decide(ctx context.Context, request *Call) (r string, err error)

	Fail(ctx context.Context, request *Call) (r string, err error)

	Revoke(ctx context.Context, request *Call) (r string, err error)

	Participation(ctx context.Context, request *Call) (r string, err error)

	Contribute(ctx context.Context, request *Call) (r string, err error)

	Maintain(ctx context.Context, request *Call) (r string, err error)

	History(ctx context.Context, request *Call) (r string, err error)

	Recall(ctx context.Context, request *Call) (r string, err error)

	Admin(ctx context.Context, request *Call) (r string, err error)
}

type MemoryStatusArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryStatusArgs() *MemoryStatusArgs {
	return &MemoryStatusArgs{}
}

func (p *MemoryStatusArgs) InitDefault() {
}

var MemoryStatusArgs_Request_DEFAULT *Call

func (p *MemoryStatusArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryStatusArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryStatusArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryStatusArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryStatusArgs(%+v)", *p)
}

var fieldIDToName_MemoryStatusArgs = map[int16]string{
	1: "request",
}

type MemoryStatusResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryStatusResult() *MemoryStatusResult {
	return &MemoryStatusResult{}
}

func (p *MemoryStatusResult) InitDefault() {
}

var MemoryStatusResult_Success_DEFAULT string

func (p *MemoryStatusResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryStatusResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryStatusResult(%+v)", *p)
}

var fieldIDToName_MemoryStatusResult = map[int16]string{
	0: "success",
}

type MemorySearchArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemorySearchArgs() *MemorySearchArgs {
	return &MemorySearchArgs{}
}

func (p *MemorySearchArgs) InitDefault() {
}

var MemorySearchArgs_Request_DEFAULT *Call

func (p *MemorySearchArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemorySearchArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemorySearchArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemorySearchArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemorySearchArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemorySearchArgs(%+v)", *p)
}

var fieldIDToName_MemorySearchArgs = map[int16]string{
	1: "request",
}

type MemorySearchResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemorySearchResult() *MemorySearchResult {
	return &MemorySearchResult{}
}

func (p *MemorySearchResult) InitDefault() {
}

var MemorySearchResult_Success_DEFAULT string

func (p *MemorySearchResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemorySearchResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemorySearchResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemorySearchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemorySearchResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemorySearchResult(%+v)", *p)
}

var fieldIDToName_MemorySearchResult = map[int16]string{
	0: "success",
}

type MemoryReadArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryReadArgs() *MemoryReadArgs {
	return &MemoryReadArgs{}
}

func (p *MemoryReadArgs) InitDefault() {
}

var MemoryReadArgs_Request_DEFAULT *Call

func (p *MemoryReadArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryReadArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryReadArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryReadArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryReadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryReadArgs(%+v)", *p)
}

var fieldIDToName_MemoryReadArgs = map[int16]string{
	1: "request",
}

type MemoryReadResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryReadResult() *MemoryReadResult {
	return &MemoryReadResult{}
}

func (p *MemoryReadResult) InitDefault() {
}

var MemoryReadResult_Success_DEFAULT string

func (p *MemoryReadResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryReadResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryReadResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryReadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryReadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryReadResult(%+v)", *p)
}

var fieldIDToName_MemoryReadResult = map[int16]string{
	0: "success",
}

type MemoryProposeArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryProposeArgs() *MemoryProposeArgs {
	return &MemoryProposeArgs{}
}

func (p *MemoryProposeArgs) InitDefault() {
}

var MemoryProposeArgs_Request_DEFAULT *Call

func (p *MemoryProposeArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryProposeArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryProposeArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryProposeArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryProposeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryProposeArgs(%+v)", *p)
}

var fieldIDToName_MemoryProposeArgs = map[int16]string{
	1: "request",
}

type MemoryProposeResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryProposeResult() *MemoryProposeResult {
	return &MemoryProposeResult{}
}

func (p *MemoryProposeResult) InitDefault() {
}

var MemoryProposeResult_Success_DEFAULT string

func (p *MemoryProposeResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryProposeResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryProposeResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryProposeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryProposeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryProposeResult(%+v)", *p)
}

var fieldIDToName_MemoryProposeResult = map[int16]string{
	0: "success",
}

type MemoryResultArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryResultArgs() *MemoryResultArgs {
	return &MemoryResultArgs{}
}

func (p *MemoryResultArgs) InitDefault() {
}

var MemoryResultArgs_Request_DEFAULT *Call

func (p *MemoryResultArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryResultArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryResultArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryResultArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryResultArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryResultArgs(%+v)", *p)
}

var fieldIDToName_MemoryResultArgs = map[int16]string{
	1: "request",
}

type MemoryResultResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryResultResult() *MemoryResultResult {
	return &MemoryResultResult{}
}

func (p *MemoryResultResult) InitDefault() {
}

var MemoryResultResult_Success_DEFAULT string

func (p *MemoryResultResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryResultResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryResultResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryResultResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryResultResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryResultResult(%+v)", *p)
}

var fieldIDToName_MemoryResultResult = map[int16]string{
	0: "success",
}

type MemoryClaimArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryClaimArgs() *MemoryClaimArgs {
	return &MemoryClaimArgs{}
}

func (p *MemoryClaimArgs) InitDefault() {
}

var MemoryClaimArgs_Request_DEFAULT *Call

func (p *MemoryClaimArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryClaimArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryClaimArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryClaimArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryClaimArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryClaimArgs(%+v)", *p)
}

var fieldIDToName_MemoryClaimArgs = map[int16]string{
	1: "request",
}

type MemoryClaimResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryClaimResult() *MemoryClaimResult {
	return &MemoryClaimResult{}
}

func (p *MemoryClaimResult) InitDefault() {
}

var MemoryClaimResult_Success_DEFAULT string

func (p *MemoryClaimResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryClaimResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryClaimResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryClaimResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryClaimResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryClaimResult(%+v)", *p)
}

var fieldIDToName_MemoryClaimResult = map[int16]string{
	0: "success",
}

type MemoryDecideArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryDecideArgs() *MemoryDecideArgs {
	return &MemoryDecideArgs{}
}

func (p *MemoryDecideArgs) InitDefault() {
}

var MemoryDecideArgs_Request_DEFAULT *Call

func (p *MemoryDecideArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryDecideArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryDecideArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryDecideArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryDecideArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryDecideArgs(%+v)", *p)
}

var fieldIDToName_MemoryDecideArgs = map[int16]string{
	1: "request",
}

type MemoryDecideResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryDecideResult() *MemoryDecideResult {
	return &MemoryDecideResult{}
}

func (p *MemoryDecideResult) InitDefault() {
}

var MemoryDecideResult_Success_DEFAULT string

func (p *MemoryDecideResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryDecideResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryDecideResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryDecideResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryDecideResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryDecideResult(%+v)", *p)
}

var fieldIDToName_MemoryDecideResult = map[int16]string{
	0: "success",
}

type MemoryFailArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryFailArgs() *MemoryFailArgs {
	return &MemoryFailArgs{}
}

func (p *MemoryFailArgs) InitDefault() {
}

var MemoryFailArgs_Request_DEFAULT *Call

func (p *MemoryFailArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryFailArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryFailArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryFailArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryFailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryFailArgs(%+v)", *p)
}

var fieldIDToName_MemoryFailArgs = map[int16]string{
	1: "request",
}

type MemoryFailResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryFailResult() *MemoryFailResult {
	return &MemoryFailResult{}
}

func (p *MemoryFailResult) InitDefault() {
}

var MemoryFailResult_Success_DEFAULT string

func (p *MemoryFailResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryFailResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryFailResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryFailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryFailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryFailResult(%+v)", *p)
}

var fieldIDToName_MemoryFailResult = map[int16]string{
	0: "success",
}

type MemoryRevokeArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryRevokeArgs() *MemoryRevokeArgs {
	return &MemoryRevokeArgs{}
}

func (p *MemoryRevokeArgs) InitDefault() {
}

var MemoryRevokeArgs_Request_DEFAULT *Call

func (p *MemoryRevokeArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryRevokeArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryRevokeArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryRevokeArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryRevokeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryRevokeArgs(%+v)", *p)
}

var fieldIDToName_MemoryRevokeArgs = map[int16]string{
	1: "request",
}

type MemoryRevokeResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryRevokeResult() *MemoryRevokeResult {
	return &MemoryRevokeResult{}
}

func (p *MemoryRevokeResult) InitDefault() {
}

var MemoryRevokeResult_Success_DEFAULT string

func (p *MemoryRevokeResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryRevokeResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryRevokeResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryRevokeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryRevokeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryRevokeResult(%+v)", *p)
}

var fieldIDToName_MemoryRevokeResult = map[int16]string{
	0: "success",
}

type MemoryParticipationArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryParticipationArgs() *MemoryParticipationArgs {
	return &MemoryParticipationArgs{}
}

func (p *MemoryParticipationArgs) InitDefault() {
}

var MemoryParticipationArgs_Request_DEFAULT *Call

func (p *MemoryParticipationArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryParticipationArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryParticipationArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryParticipationArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryParticipationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryParticipationArgs(%+v)", *p)
}

var fieldIDToName_MemoryParticipationArgs = map[int16]string{
	1: "request",
}

type MemoryParticipationResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryParticipationResult() *MemoryParticipationResult {
	return &MemoryParticipationResult{}
}

func (p *MemoryParticipationResult) InitDefault() {
}

var MemoryParticipationResult_Success_DEFAULT string

func (p *MemoryParticipationResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryParticipationResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryParticipationResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryParticipationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryParticipationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryParticipationResult(%+v)", *p)
}

var fieldIDToName_MemoryParticipationResult = map[int16]string{
	0: "success",
}

type MemoryContributeArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryContributeArgs() *MemoryContributeArgs {
	return &MemoryContributeArgs{}
}

func (p *MemoryContributeArgs) InitDefault() {
}

var MemoryContributeArgs_Request_DEFAULT *Call

func (p *MemoryContributeArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryContributeArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryContributeArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryContributeArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryContributeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryContributeArgs(%+v)", *p)
}

var fieldIDToName_MemoryContributeArgs = map[int16]string{
	1: "request",
}

type MemoryContributeResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryContributeResult() *MemoryContributeResult {
	return &MemoryContributeResult{}
}

func (p *MemoryContributeResult) InitDefault() {
}

var MemoryContributeResult_Success_DEFAULT string

func (p *MemoryContributeResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryContributeResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryContributeResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryContributeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryContributeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryContributeResult(%+v)", *p)
}

var fieldIDToName_MemoryContributeResult = map[int16]string{
	0: "success",
}

type MemoryMaintainArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryMaintainArgs() *MemoryMaintainArgs {
	return &MemoryMaintainArgs{}
}

func (p *MemoryMaintainArgs) InitDefault() {
}

var MemoryMaintainArgs_Request_DEFAULT *Call

func (p *MemoryMaintainArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryMaintainArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryMaintainArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryMaintainArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryMaintainArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryMaintainArgs(%+v)", *p)
}

var fieldIDToName_MemoryMaintainArgs = map[int16]string{
	1: "request",
}

type MemoryMaintainResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryMaintainResult() *MemoryMaintainResult {
	return &MemoryMaintainResult{}
}

func (p *MemoryMaintainResult) InitDefault() {
}

var MemoryMaintainResult_Success_DEFAULT string

func (p *MemoryMaintainResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryMaintainResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryMaintainResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryMaintainResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryMaintainResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryMaintainResult(%+v)", *p)
}

var fieldIDToName_MemoryMaintainResult = map[int16]string{
	0: "success",
}

type MemoryHistoryArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryHistoryArgs() *MemoryHistoryArgs {
	return &MemoryHistoryArgs{}
}

func (p *MemoryHistoryArgs) InitDefault() {
}

var MemoryHistoryArgs_Request_DEFAULT *Call

func (p *MemoryHistoryArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryHistoryArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryHistoryArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryHistoryArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryHistoryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryHistoryArgs(%+v)", *p)
}

var fieldIDToName_MemoryHistoryArgs = map[int16]string{
	1: "request",
}

type MemoryHistoryResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryHistoryResult() *MemoryHistoryResult {
	return &MemoryHistoryResult{}
}

func (p *MemoryHistoryResult) InitDefault() {
}

var MemoryHistoryResult_Success_DEFAULT string

func (p *MemoryHistoryResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryHistoryResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryHistoryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryHistoryResult(%+v)", *p)
}

var fieldIDToName_MemoryHistoryResult = map[int16]string{
	0: "success",
}

type MemoryRecallArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryRecallArgs() *MemoryRecallArgs {
	return &MemoryRecallArgs{}
}

func (p *MemoryRecallArgs) InitDefault() {
}

var MemoryRecallArgs_Request_DEFAULT *Call

func (p *MemoryRecallArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryRecallArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryRecallArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryRecallArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryRecallArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryRecallArgs(%+v)", *p)
}

var fieldIDToName_MemoryRecallArgs = map[int16]string{
	1: "request",
}

type MemoryRecallResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryRecallResult() *MemoryRecallResult {
	return &MemoryRecallResult{}
}

func (p *MemoryRecallResult) InitDefault() {
}

var MemoryRecallResult_Success_DEFAULT string

func (p *MemoryRecallResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryRecallResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryRecallResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryRecallResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryRecallResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryRecallResult(%+v)", *p)
}

var fieldIDToName_MemoryRecallResult = map[int16]string{
	0: "success",
}

type MemoryAdminArgs struct {
	Request *Call `thrift:"request,1" frugal:"1,default,Call" json:"request"`
}

func NewMemoryAdminArgs() *MemoryAdminArgs {
	return &MemoryAdminArgs{}
}

func (p *MemoryAdminArgs) InitDefault() {
}

var MemoryAdminArgs_Request_DEFAULT *Call

func (p *MemoryAdminArgs) GetRequest() (v *Call) {
	if !p.IsSetRequest() {
		return MemoryAdminArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MemoryAdminArgs) SetRequest(val *Call) {
	p.Request = val
}

func (p *MemoryAdminArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MemoryAdminArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryAdminArgs(%+v)", *p)
}

var fieldIDToName_MemoryAdminArgs = map[int16]string{
	1: "request",
}

type MemoryAdminResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewMemoryAdminResult() *MemoryAdminResult {
	return &MemoryAdminResult{}
}

func (p *MemoryAdminResult) InitDefault() {
}

var MemoryAdminResult_Success_DEFAULT string

func (p *MemoryAdminResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return MemoryAdminResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *MemoryAdminResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *MemoryAdminResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MemoryAdminResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryAdminResult(%+v)", *p)
}

var fieldIDToName_MemoryAdminResult = map[int16]string{
	0: "success",
}
