package web

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"slices"
	"strings"
	"time"

	"github.com/juex-ai/juex/internal/app"
	"github.com/juex-ai/juex/internal/app/config"
)

// GenerateModuleTypeScript emits the inspection contract and payloads from Go
// JSON declarations. Unsupported kinds fail rather than silently inventing TS.
func GenerateModuleTypeScript() ([]byte, error) {
	catalog, err := app.ThreadInspectionCatalog(config.Config{})
	if err != nil {
		return nil, err
	}
	g := moduleTypeGenerator{types: map[string]reflect.Type{}}
	if _, err := g.render(reflect.TypeFor[ThreadModulesSnapshot]()); err != nil {
		return nil, err
	}
	payloads := catalog.StateTypes()
	ids := make([]string, 0, len(payloads))
	for id := range payloads {
		ids = append(ids, string(id))
	}
	slices.Sort(ids)
	var mapping strings.Builder
	mapping.WriteString("export interface ModulePayloads {\n")
	for _, id := range ids {
		var sample any
		for key, value := range payloads {
			if string(key) == id {
				sample = value
				break
			}
		}
		typ := reflect.TypeOf(sample)
		if typ.Kind() == reflect.Pointer {
			typ = typ.Elem()
		}
		name, err := g.render(typ)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&mapping, "  %q: %s;\n", id, name)
	}
	mapping.WriteString("}\n")
	var out bytes.Buffer
	out.WriteString("// Code generated by go run ./scripts/gen-module-schema. DO NOT EDIT.\n\n")
	// Rendering a struct may discover other named structs.
	rendered := map[string]string{}
	for len(rendered) < len(g.types) {
		for name, typ := range g.types {
			if _, ok := rendered[name]; ok {
				continue
			}
			body, err := g.structure(typ)
			if err != nil {
				return nil, err
			}
			rendered[name] = body
		}
	}
	names := make([]string, 0, len(rendered))
	for name := range rendered {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		fmt.Fprintf(&out, "export interface %s %s\n", name, rendered[name])
	}
	out.WriteString(mapping.String())
	return out.Bytes(), nil
}

type moduleTypeGenerator struct{ types map[string]reflect.Type }

func (g *moduleTypeGenerator) render(t reflect.Type) (string, error) {
	if t == reflect.TypeFor[time.Time]() {
		return "string", nil
	}
	if t == reflect.TypeFor[json.RawMessage]() {
		return "unknown", nil
	}
	switch t.Kind() {
	case reflect.Pointer:
		inner, err := g.render(t.Elem())
		return inner + " | null", err
	case reflect.String:
		return "string", nil
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.Slice:
		inner, err := g.render(t.Elem())
		return "Array<" + inner + ">", err
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			return "", fmt.Errorf("unsupported schema map key %s", t)
		}
		inner, err := g.render(t.Elem())
		return "Record<string, " + inner + ">", err
	case reflect.Struct:
		if old, ok := g.types[t.Name()]; ok && old != t {
			return "", fmt.Errorf("schema name collision %s", t.Name())
		}
		g.types[t.Name()] = t
		return t.Name(), nil
	default:
		return "", fmt.Errorf("unsupported module schema type %s", t)
	}
}
func (g *moduleTypeGenerator) structure(t reflect.Type) (string, error) {
	var out strings.Builder
	out.WriteString("{\n")
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := strings.Split(field.Tag.Get("json"), ",")
		if tag[0] == "-" {
			continue
		}
		if tag[0] == "" {
			return "", fmt.Errorf("missing JSON tag on %s.%s", t, field.Name)
		}
		name := tag[0]
		if slices.Contains(tag[1:], "omitempty") {
			name += "?"
		}
		kind, err := g.render(field.Type)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&out, "  %s: %s;\n", name, kind)
	}
	out.WriteString("}\n")
	return out.String(), nil
}
