// Code generated by Kitex v0.16.3. DO NOT EDIT.

package memory

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Maintain(ctx context.Context, scopeJSON string, threadID string, reason string, commandID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Contribute(ctx context.Context, scopeJSON string, contributionJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Reviews(ctx context.Context, accessJSON string, offset int32, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	StorageRules(ctx context.Context, accessJSON string, offset int32, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Health(ctx context.Context, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Status(ctx context.Context, accessJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Configure(ctx context.Context, accessJSON string, version int64, enabled bool, strategy string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Search(ctx context.Context, accessJSON string, queryJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Read(ctx context.Context, accessJSON string, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Facts(ctx context.Context, accessJSON string, queryJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Domains(ctx context.Context, accessJSON string, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Propose(ctx context.Context, scopeJSON string, threadID string, proposalJSON string, automatic bool, commandID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Review(ctx context.Context, scopeJSON string, bindingJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Decide(ctx context.Context, scopeJSON string, bindingJSON string, decisionJSON string, commandID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	CancelCommand(ctx context.Context, scopeJSON string, commandID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	ReviewResult_(ctx context.Context, accessJSON string, threadID string, reviewID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Administer(ctx context.Context, accessJSON string, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kMemoryClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMemoryClient struct {
	*kClient
}

func (p *kMemoryClient) Maintain(ctx context.Context, scopeJSON string, threadID string, reason string, commandID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Maintain(ctx, scopeJSON, threadID, reason, commandID)
}

func (p *kMemoryClient) Contribute(ctx context.Context, scopeJSON string, contributionJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Contribute(ctx, scopeJSON, contributionJSON)
}

func (p *kMemoryClient) Reviews(ctx context.Context, accessJSON string, offset int32, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Reviews(ctx, accessJSON, offset, limit)
}

func (p *kMemoryClient) StorageRules(ctx context.Context, accessJSON string, offset int32, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StorageRules(ctx, accessJSON, offset, limit)
}

func (p *kMemoryClient) Health(ctx context.Context, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx)
}

func (p *kMemoryClient) Status(ctx context.Context, accessJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Status(ctx, accessJSON)
}

func (p *kMemoryClient) Configure(ctx context.Context, accessJSON string, version int64, enabled bool, strategy string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Configure(ctx, accessJSON, version, enabled, strategy)
}

func (p *kMemoryClient) Search(ctx context.Context, accessJSON string, queryJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Search(ctx, accessJSON, queryJSON)
}

func (p *kMemoryClient) Read(ctx context.Context, accessJSON string, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Read(ctx, accessJSON, requestJSON)
}

func (p *kMemoryClient) Facts(ctx context.Context, accessJSON string, queryJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Facts(ctx, accessJSON, queryJSON)
}

func (p *kMemoryClient) Domains(ctx context.Context, accessJSON string, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Domains(ctx, accessJSON, requestJSON)
}

func (p *kMemoryClient) Propose(ctx context.Context, scopeJSON string, threadID string, proposalJSON string, automatic bool, commandID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Propose(ctx, scopeJSON, threadID, proposalJSON, automatic, commandID)
}

func (p *kMemoryClient) Review(ctx context.Context, scopeJSON string, bindingJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Review(ctx, scopeJSON, bindingJSON)
}

func (p *kMemoryClient) Decide(ctx context.Context, scopeJSON string, bindingJSON string, decisionJSON string, commandID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Decide(ctx, scopeJSON, bindingJSON, decisionJSON, commandID)
}

func (p *kMemoryClient) CancelCommand(ctx context.Context, scopeJSON string, commandID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelCommand(ctx, scopeJSON, commandID)
}

func (p *kMemoryClient) ReviewResult_(ctx context.Context, accessJSON string, threadID string, reviewID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReviewResult_(ctx, accessJSON, threadID, reviewID)
}

func (p *kMemoryClient) Administer(ctx context.Context, accessJSON string, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Administer(ctx, accessJSON, requestJSON)
}
