// Code generated by Kitex v0.16.3. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Recall": kitex.NewMethodInfo(
		recallHandler,
		newMemoryRecallArgs,
		newMemoryRecallResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Maintain": kitex.NewMethodInfo(
		maintainHandler,
		newMemoryMaintainArgs,
		newMemoryMaintainResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Contribute": kitex.NewMethodInfo(
		contributeHandler,
		newMemoryContributeArgs,
		newMemoryContributeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Reviews": kitex.NewMethodInfo(
		reviewsHandler,
		newMemoryReviewsArgs,
		newMemoryReviewsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StorageRules": kitex.NewMethodInfo(
		storageRulesHandler,
		newMemoryStorageRulesArgs,
		newMemoryStorageRulesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newMemoryHealthArgs,
		newMemoryHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Status": kitex.NewMethodInfo(
		statusHandler,
		newMemoryStatusArgs,
		newMemoryStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Configure": kitex.NewMethodInfo(
		configureHandler,
		newMemoryConfigureArgs,
		newMemoryConfigureResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Search": kitex.NewMethodInfo(
		searchHandler,
		newMemorySearchArgs,
		newMemorySearchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Read": kitex.NewMethodInfo(
		readHandler,
		newMemoryReadArgs,
		newMemoryReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Facts": kitex.NewMethodInfo(
		factsHandler,
		newMemoryFactsArgs,
		newMemoryFactsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Domains": kitex.NewMethodInfo(
		domainsHandler,
		newMemoryDomainsArgs,
		newMemoryDomainsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Propose": kitex.NewMethodInfo(
		proposeHandler,
		newMemoryProposeArgs,
		newMemoryProposeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Review": kitex.NewMethodInfo(
		reviewHandler,
		newMemoryReviewArgs,
		newMemoryReviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Decide": kitex.NewMethodInfo(
		decideHandler,
		newMemoryDecideArgs,
		newMemoryDecideResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelCommand": kitex.NewMethodInfo(
		cancelCommandHandler,
		newMemoryCancelCommandArgs,
		newMemoryCancelCommandResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReviewResult": kitex.NewMethodInfo(
		reviewResult_Handler,
		newMemoryReviewResultArgs,
		newMemoryReviewResultResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Administer": kitex.NewMethodInfo(
		administerHandler,
		newMemoryAdministerArgs,
		newMemoryAdministerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	memoryServiceInfo                = NewServiceInfo()
	memoryServiceInfoForClient       = NewServiceInfoForClient()
	memoryServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return memoryServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return memoryServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return memoryServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Memory"
	handlerType := (*platform.Memory)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "platform",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func recallHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryRecallArgs)
	realResult := result.(*platform.MemoryRecallResult)
	success, err := handler.(platform.Memory).Recall(ctx, realArg.AccessJSON, realArg.Query)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryRecallArgs() interface{} {
	return platform.NewMemoryRecallArgs()
}

func newMemoryRecallResult() interface{} {
	return platform.NewMemoryRecallResult()
}

func maintainHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryMaintainArgs)
	realResult := result.(*platform.MemoryMaintainResult)
	success, err := handler.(platform.Memory).Maintain(ctx, realArg.ScopeJSON, realArg.ThreadID, realArg.Reason, realArg.CommandID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryMaintainArgs() interface{} {
	return platform.NewMemoryMaintainArgs()
}

func newMemoryMaintainResult() interface{} {
	return platform.NewMemoryMaintainResult()
}

func contributeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryContributeArgs)
	realResult := result.(*platform.MemoryContributeResult)
	success, err := handler.(platform.Memory).Contribute(ctx, realArg.ScopeJSON, realArg.ContributionJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryContributeArgs() interface{} {
	return platform.NewMemoryContributeArgs()
}

func newMemoryContributeResult() interface{} {
	return platform.NewMemoryContributeResult()
}

func reviewsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryReviewsArgs)
	realResult := result.(*platform.MemoryReviewsResult)
	success, err := handler.(platform.Memory).Reviews(ctx, realArg.AccessJSON, realArg.Offset, realArg.Limit)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryReviewsArgs() interface{} {
	return platform.NewMemoryReviewsArgs()
}

func newMemoryReviewsResult() interface{} {
	return platform.NewMemoryReviewsResult()
}

func storageRulesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryStorageRulesArgs)
	realResult := result.(*platform.MemoryStorageRulesResult)
	success, err := handler.(platform.Memory).StorageRules(ctx, realArg.AccessJSON, realArg.Offset, realArg.Limit)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryStorageRulesArgs() interface{} {
	return platform.NewMemoryStorageRulesArgs()
}

func newMemoryStorageRulesResult() interface{} {
	return platform.NewMemoryStorageRulesResult()
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*platform.MemoryHealthArgs)
	realResult := result.(*platform.MemoryHealthResult)
	success, err := handler.(platform.Memory).Health(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryHealthArgs() interface{} {
	return platform.NewMemoryHealthArgs()
}

func newMemoryHealthResult() interface{} {
	return platform.NewMemoryHealthResult()
}

func statusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryStatusArgs)
	realResult := result.(*platform.MemoryStatusResult)
	success, err := handler.(platform.Memory).Status(ctx, realArg.AccessJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryStatusArgs() interface{} {
	return platform.NewMemoryStatusArgs()
}

func newMemoryStatusResult() interface{} {
	return platform.NewMemoryStatusResult()
}

func configureHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryConfigureArgs)
	realResult := result.(*platform.MemoryConfigureResult)
	success, err := handler.(platform.Memory).Configure(ctx, realArg.AccessJSON, realArg.Version, realArg.Enabled, realArg.Strategy)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryConfigureArgs() interface{} {
	return platform.NewMemoryConfigureArgs()
}

func newMemoryConfigureResult() interface{} {
	return platform.NewMemoryConfigureResult()
}

func searchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemorySearchArgs)
	realResult := result.(*platform.MemorySearchResult)
	success, err := handler.(platform.Memory).Search(ctx, realArg.AccessJSON, realArg.QueryJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemorySearchArgs() interface{} {
	return platform.NewMemorySearchArgs()
}

func newMemorySearchResult() interface{} {
	return platform.NewMemorySearchResult()
}

func readHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryReadArgs)
	realResult := result.(*platform.MemoryReadResult)
	success, err := handler.(platform.Memory).Read(ctx, realArg.AccessJSON, realArg.RequestJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryReadArgs() interface{} {
	return platform.NewMemoryReadArgs()
}

func newMemoryReadResult() interface{} {
	return platform.NewMemoryReadResult()
}

func factsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryFactsArgs)
	realResult := result.(*platform.MemoryFactsResult)
	success, err := handler.(platform.Memory).Facts(ctx, realArg.AccessJSON, realArg.QueryJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryFactsArgs() interface{} {
	return platform.NewMemoryFactsArgs()
}

func newMemoryFactsResult() interface{} {
	return platform.NewMemoryFactsResult()
}

func domainsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryDomainsArgs)
	realResult := result.(*platform.MemoryDomainsResult)
	success, err := handler.(platform.Memory).Domains(ctx, realArg.AccessJSON, realArg.RequestJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryDomainsArgs() interface{} {
	return platform.NewMemoryDomainsArgs()
}

func newMemoryDomainsResult() interface{} {
	return platform.NewMemoryDomainsResult()
}

func proposeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryProposeArgs)
	realResult := result.(*platform.MemoryProposeResult)
	success, err := handler.(platform.Memory).Propose(ctx, realArg.ScopeJSON, realArg.ThreadID, realArg.ProposalJSON, realArg.Automatic, realArg.CommandID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryProposeArgs() interface{} {
	return platform.NewMemoryProposeArgs()
}

func newMemoryProposeResult() interface{} {
	return platform.NewMemoryProposeResult()
}

func reviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryReviewArgs)
	realResult := result.(*platform.MemoryReviewResult)
	success, err := handler.(platform.Memory).Review(ctx, realArg.ScopeJSON, realArg.BindingJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryReviewArgs() interface{} {
	return platform.NewMemoryReviewArgs()
}

func newMemoryReviewResult() interface{} {
	return platform.NewMemoryReviewResult()
}

func decideHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryDecideArgs)
	realResult := result.(*platform.MemoryDecideResult)
	success, err := handler.(platform.Memory).Decide(ctx, realArg.ScopeJSON, realArg.BindingJSON, realArg.DecisionJSON, realArg.CommandID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryDecideArgs() interface{} {
	return platform.NewMemoryDecideArgs()
}

func newMemoryDecideResult() interface{} {
	return platform.NewMemoryDecideResult()
}

func cancelCommandHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryCancelCommandArgs)
	realResult := result.(*platform.MemoryCancelCommandResult)
	success, err := handler.(platform.Memory).CancelCommand(ctx, realArg.ScopeJSON, realArg.CommandID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryCancelCommandArgs() interface{} {
	return platform.NewMemoryCancelCommandArgs()
}

func newMemoryCancelCommandResult() interface{} {
	return platform.NewMemoryCancelCommandResult()
}

func reviewResult_Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryReviewResultArgs)
	realResult := result.(*platform.MemoryReviewResultResult)
	success, err := handler.(platform.Memory).ReviewResult_(ctx, realArg.AccessJSON, realArg.ThreadID, realArg.ReviewID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryReviewResultArgs() interface{} {
	return platform.NewMemoryReviewResultArgs()
}

func newMemoryReviewResultResult() interface{} {
	return platform.NewMemoryReviewResultResult()
}

func administerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.MemoryAdministerArgs)
	realResult := result.(*platform.MemoryAdministerResult)
	success, err := handler.(platform.Memory).Administer(ctx, realArg.AccessJSON, realArg.RequestJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMemoryAdministerArgs() interface{} {
	return platform.NewMemoryAdministerArgs()
}

func newMemoryAdministerResult() interface{} {
	return platform.NewMemoryAdministerResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Recall(ctx context.Context, accessJSON string, query string) (r *platform.Reply, err error) {
	var _args platform.MemoryRecallArgs
	_args.AccessJSON = accessJSON
	_args.Query = query
	var _result platform.MemoryRecallResult
	if err = p.c.Call(ctx, "Recall", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Maintain(ctx context.Context, scopeJSON string, threadID string, reason string, commandID string) (r *platform.Reply, err error) {
	var _args platform.MemoryMaintainArgs
	_args.ScopeJSON = scopeJSON
	_args.ThreadID = threadID
	_args.Reason = reason
	_args.CommandID = commandID
	var _result platform.MemoryMaintainResult
	if err = p.c.Call(ctx, "Maintain", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Contribute(ctx context.Context, scopeJSON string, contributionJSON string) (r *platform.Reply, err error) {
	var _args platform.MemoryContributeArgs
	_args.ScopeJSON = scopeJSON
	_args.ContributionJSON = contributionJSON
	var _result platform.MemoryContributeResult
	if err = p.c.Call(ctx, "Contribute", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Reviews(ctx context.Context, accessJSON string, offset int32, limit int32) (r *platform.Reply, err error) {
	var _args platform.MemoryReviewsArgs
	_args.AccessJSON = accessJSON
	_args.Offset = offset
	_args.Limit = limit
	var _result platform.MemoryReviewsResult
	if err = p.c.Call(ctx, "Reviews", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StorageRules(ctx context.Context, accessJSON string, offset int32, limit int32) (r *platform.Reply, err error) {
	var _args platform.MemoryStorageRulesArgs
	_args.AccessJSON = accessJSON
	_args.Offset = offset
	_args.Limit = limit
	var _result platform.MemoryStorageRulesResult
	if err = p.c.Call(ctx, "StorageRules", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context) (r *platform.Reply, err error) {
	var _args platform.MemoryHealthArgs
	var _result platform.MemoryHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Status(ctx context.Context, accessJSON string) (r *platform.Reply, err error) {
	var _args platform.MemoryStatusArgs
	_args.AccessJSON = accessJSON
	var _result platform.MemoryStatusResult
	if err = p.c.Call(ctx, "Status", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Configure(ctx context.Context, accessJSON string, version int64, enabled bool, strategy string) (r *platform.Reply, err error) {
	var _args platform.MemoryConfigureArgs
	_args.AccessJSON = accessJSON
	_args.Version = version
	_args.Enabled = enabled
	_args.Strategy = strategy
	var _result platform.MemoryConfigureResult
	if err = p.c.Call(ctx, "Configure", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Search(ctx context.Context, accessJSON string, queryJSON string) (r *platform.Reply, err error) {
	var _args platform.MemorySearchArgs
	_args.AccessJSON = accessJSON
	_args.QueryJSON = queryJSON
	var _result platform.MemorySearchResult
	if err = p.c.Call(ctx, "Search", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Read(ctx context.Context, accessJSON string, requestJSON string) (r *platform.Reply, err error) {
	var _args platform.MemoryReadArgs
	_args.AccessJSON = accessJSON
	_args.RequestJSON = requestJSON
	var _result platform.MemoryReadResult
	if err = p.c.Call(ctx, "Read", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Facts(ctx context.Context, accessJSON string, queryJSON string) (r *platform.Reply, err error) {
	var _args platform.MemoryFactsArgs
	_args.AccessJSON = accessJSON
	_args.QueryJSON = queryJSON
	var _result platform.MemoryFactsResult
	if err = p.c.Call(ctx, "Facts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Domains(ctx context.Context, accessJSON string, requestJSON string) (r *platform.Reply, err error) {
	var _args platform.MemoryDomainsArgs
	_args.AccessJSON = accessJSON
	_args.RequestJSON = requestJSON
	var _result platform.MemoryDomainsResult
	if err = p.c.Call(ctx, "Domains", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Propose(ctx context.Context, scopeJSON string, threadID string, proposalJSON string, automatic bool, commandID string) (r *platform.Reply, err error) {
	var _args platform.MemoryProposeArgs
	_args.ScopeJSON = scopeJSON
	_args.ThreadID = threadID
	_args.ProposalJSON = proposalJSON
	_args.Automatic = automatic
	_args.CommandID = commandID
	var _result platform.MemoryProposeResult
	if err = p.c.Call(ctx, "Propose", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Review(ctx context.Context, scopeJSON string, bindingJSON string) (r *platform.Reply, err error) {
	var _args platform.MemoryReviewArgs
	_args.ScopeJSON = scopeJSON
	_args.BindingJSON = bindingJSON
	var _result platform.MemoryReviewResult
	if err = p.c.Call(ctx, "Review", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Decide(ctx context.Context, scopeJSON string, bindingJSON string, decisionJSON string, commandID string) (r *platform.Reply, err error) {
	var _args platform.MemoryDecideArgs
	_args.ScopeJSON = scopeJSON
	_args.BindingJSON = bindingJSON
	_args.DecisionJSON = decisionJSON
	_args.CommandID = commandID
	var _result platform.MemoryDecideResult
	if err = p.c.Call(ctx, "Decide", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelCommand(ctx context.Context, scopeJSON string, commandID string) (r *platform.Reply, err error) {
	var _args platform.MemoryCancelCommandArgs
	_args.ScopeJSON = scopeJSON
	_args.CommandID = commandID
	var _result platform.MemoryCancelCommandResult
	if err = p.c.Call(ctx, "CancelCommand", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReviewResult_(ctx context.Context, accessJSON string, threadID string, reviewID string) (r *platform.Reply, err error) {
	var _args platform.MemoryReviewResultArgs
	_args.AccessJSON = accessJSON
	_args.ThreadID = threadID
	_args.ReviewID = reviewID
	var _result platform.MemoryReviewResultResult
	if err = p.c.Call(ctx, "ReviewResult", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Administer(ctx context.Context, accessJSON string, requestJSON string) (r *platform.Reply, err error) {
	var _args platform.MemoryAdministerArgs
	_args.AccessJSON = accessJSON
	_args.RequestJSON = requestJSON
	var _result platform.MemoryAdministerResult
	if err = p.c.Call(ctx, "Administer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
