events {}
http {
  server {
    listen 443 ssl;
    ssl_certificate /run/juex/tls/certificate.pem;
    ssl_certificate_key /run/juex/tls/key.pem;
    ssl_protocols TLSv1.3;
    client_max_body_size 4m;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_read_timeout 300s;
    location /device/ {
      proxy_pass http://execution:8683;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
    location / {
      proxy_pass http://management:8680;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
