// Code generated by Kitex v0.16.3. DO NOT EDIT.

package memory

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	memorywire "github.com/juex-ai/juex/internal/foundation/memoryclient/wire/memorywire"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Status(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Search(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Read(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Propose(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Result_(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Claim(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Decide(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Fail(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Revoke(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Participation(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Contribute(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Maintain(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	History(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Recall(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
	Admin(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kMemoryClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMemoryClient struct {
	*kClient
}

func (p *kMemoryClient) Status(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Status(ctx, request)
}

func (p *kMemoryClient) Search(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Search(ctx, request)
}

func (p *kMemoryClient) Read(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Read(ctx, request)
}

func (p *kMemoryClient) Propose(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Propose(ctx, request)
}

func (p *kMemoryClient) Result_(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Result_(ctx, request)
}

func (p *kMemoryClient) Claim(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Claim(ctx, request)
}

func (p *kMemoryClient) Decide(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Decide(ctx, request)
}

func (p *kMemoryClient) Fail(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Fail(ctx, request)
}

func (p *kMemoryClient) Revoke(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Revoke(ctx, request)
}

func (p *kMemoryClient) Participation(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Participation(ctx, request)
}

func (p *kMemoryClient) Contribute(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Contribute(ctx, request)
}

func (p *kMemoryClient) Maintain(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Maintain(ctx, request)
}

func (p *kMemoryClient) History(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.History(ctx, request)
}

func (p *kMemoryClient) Recall(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Recall(ctx, request)
}

func (p *kMemoryClient) Admin(ctx context.Context, request *memorywire.Call, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Admin(ctx, request)
}
