// Code generated by Kitex v0.16.3. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	memorywire "github.com/juex-ai/juex/internal/foundation/memoryclient/wire/memorywire"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Status": kitex.NewMethodInfo(
		statusHandler,
		newMemoryStatusArgs,
		newMemoryStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Search": kitex.NewMethodInfo(
		searchHandler,
		newMemorySearchArgs,
		newMemorySearchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Read": kitex.NewMethodInfo(
		readHandler,
		newMemoryReadArgs,
		newMemoryReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Propose": kitex.NewMethodInfo(
		proposeHandler,
		newMemoryProposeArgs,
		newMemoryProposeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Result": kitex.NewMethodInfo(
		result_Handler,
		newMemoryResultArgs,
		newMemoryResultResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Claim": kitex.NewMethodInfo(
		claimHandler,
		newMemoryClaimArgs,
		newMemoryClaimResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Decide": kitex.NewMethodInfo(
		decideHandler,
		newMemoryDecideArgs,
		newMemoryDecideResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Fail": kitex.NewMethodInfo(
		failHandler,
		newMemoryFailArgs,
		newMemoryFailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Revoke": kitex.NewMethodInfo(
		revokeHandler,
		newMemoryRevokeArgs,
		newMemoryRevokeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Participation": kitex.NewMethodInfo(
		participationHandler,
		newMemoryParticipationArgs,
		newMemoryParticipationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Contribute": kitex.NewMethodInfo(
		contributeHandler,
		newMemoryContributeArgs,
		newMemoryContributeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Maintain": kitex.NewMethodInfo(
		maintainHandler,
		newMemoryMaintainArgs,
		newMemoryMaintainResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"History": kitex.NewMethodInfo(
		historyHandler,
		newMemoryHistoryArgs,
		newMemoryHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Recall": kitex.NewMethodInfo(
		recallHandler,
		newMemoryRecallArgs,
		newMemoryRecallResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Admin": kitex.NewMethodInfo(
		adminHandler,
		newMemoryAdminArgs,
		newMemoryAdminResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	memoryServiceInfo                = NewServiceInfo()
	memoryServiceInfoForClient       = NewServiceInfoForClient()
	memoryServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return memoryServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return memoryServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return memoryServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Memory"
	handlerType := (*memorywire.Memory)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "memorywire",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func statusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryStatusArgs)
	realResult := result.(*memorywire.MemoryStatusResult)
	success, err := handler.(memorywire.Memory).Status(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryStatusArgs() interface{} {
	return memorywire.NewMemoryStatusArgs()
}

func newMemoryStatusResult() interface{} {
	return memorywire.NewMemoryStatusResult()
}

func searchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemorySearchArgs)
	realResult := result.(*memorywire.MemorySearchResult)
	success, err := handler.(memorywire.Memory).Search(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemorySearchArgs() interface{} {
	return memorywire.NewMemorySearchArgs()
}

func newMemorySearchResult() interface{} {
	return memorywire.NewMemorySearchResult()
}

func readHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryReadArgs)
	realResult := result.(*memorywire.MemoryReadResult)
	success, err := handler.(memorywire.Memory).Read(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryReadArgs() interface{} {
	return memorywire.NewMemoryReadArgs()
}

func newMemoryReadResult() interface{} {
	return memorywire.NewMemoryReadResult()
}

func proposeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryProposeArgs)
	realResult := result.(*memorywire.MemoryProposeResult)
	success, err := handler.(memorywire.Memory).Propose(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryProposeArgs() interface{} {
	return memorywire.NewMemoryProposeArgs()
}

func newMemoryProposeResult() interface{} {
	return memorywire.NewMemoryProposeResult()
}

func result_Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryResultArgs)
	realResult := result.(*memorywire.MemoryResultResult)
	success, err := handler.(memorywire.Memory).Result_(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryResultArgs() interface{} {
	return memorywire.NewMemoryResultArgs()
}

func newMemoryResultResult() interface{} {
	return memorywire.NewMemoryResultResult()
}

func claimHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryClaimArgs)
	realResult := result.(*memorywire.MemoryClaimResult)
	success, err := handler.(memorywire.Memory).Claim(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryClaimArgs() interface{} {
	return memorywire.NewMemoryClaimArgs()
}

func newMemoryClaimResult() interface{} {
	return memorywire.NewMemoryClaimResult()
}

func decideHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryDecideArgs)
	realResult := result.(*memorywire.MemoryDecideResult)
	success, err := handler.(memorywire.Memory).Decide(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryDecideArgs() interface{} {
	return memorywire.NewMemoryDecideArgs()
}

func newMemoryDecideResult() interface{} {
	return memorywire.NewMemoryDecideResult()
}

func failHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryFailArgs)
	realResult := result.(*memorywire.MemoryFailResult)
	success, err := handler.(memorywire.Memory).Fail(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryFailArgs() interface{} {
	return memorywire.NewMemoryFailArgs()
}

func newMemoryFailResult() interface{} {
	return memorywire.NewMemoryFailResult()
}

func revokeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryRevokeArgs)
	realResult := result.(*memorywire.MemoryRevokeResult)
	success, err := handler.(memorywire.Memory).Revoke(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryRevokeArgs() interface{} {
	return memorywire.NewMemoryRevokeArgs()
}

func newMemoryRevokeResult() interface{} {
	return memorywire.NewMemoryRevokeResult()
}

func participationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryParticipationArgs)
	realResult := result.(*memorywire.MemoryParticipationResult)
	success, err := handler.(memorywire.Memory).Participation(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryParticipationArgs() interface{} {
	return memorywire.NewMemoryParticipationArgs()
}

func newMemoryParticipationResult() interface{} {
	return memorywire.NewMemoryParticipationResult()
}

func contributeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryContributeArgs)
	realResult := result.(*memorywire.MemoryContributeResult)
	success, err := handler.(memorywire.Memory).Contribute(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryContributeArgs() interface{} {
	return memorywire.NewMemoryContributeArgs()
}

func newMemoryContributeResult() interface{} {
	return memorywire.NewMemoryContributeResult()
}

func maintainHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryMaintainArgs)
	realResult := result.(*memorywire.MemoryMaintainResult)
	success, err := handler.(memorywire.Memory).Maintain(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryMaintainArgs() interface{} {
	return memorywire.NewMemoryMaintainArgs()
}

func newMemoryMaintainResult() interface{} {
	return memorywire.NewMemoryMaintainResult()
}

func historyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryHistoryArgs)
	realResult := result.(*memorywire.MemoryHistoryResult)
	success, err := handler.(memorywire.Memory).History(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryHistoryArgs() interface{} {
	return memorywire.NewMemoryHistoryArgs()
}

func newMemoryHistoryResult() interface{} {
	return memorywire.NewMemoryHistoryResult()
}

func recallHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryRecallArgs)
	realResult := result.(*memorywire.MemoryRecallResult)
	success, err := handler.(memorywire.Memory).Recall(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryRecallArgs() interface{} {
	return memorywire.NewMemoryRecallArgs()
}

func newMemoryRecallResult() interface{} {
	return memorywire.NewMemoryRecallResult()
}

func adminHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*memorywire.MemoryAdminArgs)
	realResult := result.(*memorywire.MemoryAdminResult)
	success, err := handler.(memorywire.Memory).Admin(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMemoryAdminArgs() interface{} {
	return memorywire.NewMemoryAdminArgs()
}

func newMemoryAdminResult() interface{} {
	return memorywire.NewMemoryAdminResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Status(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryStatusArgs
	_args.Request = request
	var _result memorywire.MemoryStatusResult
	if err = p.c.Call(ctx, "Status", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Search(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemorySearchArgs
	_args.Request = request
	var _result memorywire.MemorySearchResult
	if err = p.c.Call(ctx, "Search", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Read(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryReadArgs
	_args.Request = request
	var _result memorywire.MemoryReadResult
	if err = p.c.Call(ctx, "Read", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Propose(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryProposeArgs
	_args.Request = request
	var _result memorywire.MemoryProposeResult
	if err = p.c.Call(ctx, "Propose", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Result_(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryResultArgs
	_args.Request = request
	var _result memorywire.MemoryResultResult
	if err = p.c.Call(ctx, "Result", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Claim(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryClaimArgs
	_args.Request = request
	var _result memorywire.MemoryClaimResult
	if err = p.c.Call(ctx, "Claim", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Decide(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryDecideArgs
	_args.Request = request
	var _result memorywire.MemoryDecideResult
	if err = p.c.Call(ctx, "Decide", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Fail(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryFailArgs
	_args.Request = request
	var _result memorywire.MemoryFailResult
	if err = p.c.Call(ctx, "Fail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Revoke(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryRevokeArgs
	_args.Request = request
	var _result memorywire.MemoryRevokeResult
	if err = p.c.Call(ctx, "Revoke", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Participation(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryParticipationArgs
	_args.Request = request
	var _result memorywire.MemoryParticipationResult
	if err = p.c.Call(ctx, "Participation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Contribute(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryContributeArgs
	_args.Request = request
	var _result memorywire.MemoryContributeResult
	if err = p.c.Call(ctx, "Contribute", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Maintain(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryMaintainArgs
	_args.Request = request
	var _result memorywire.MemoryMaintainResult
	if err = p.c.Call(ctx, "Maintain", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) History(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryHistoryArgs
	_args.Request = request
	var _result memorywire.MemoryHistoryResult
	if err = p.c.Call(ctx, "History", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Recall(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryRecallArgs
	_args.Request = request
	var _result memorywire.MemoryRecallResult
	if err = p.c.Call(ctx, "Recall", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Admin(ctx context.Context, request *memorywire.Call) (r string, err error) {
	var _args memorywire.MemoryAdminArgs
	_args.Request = request
	var _result memorywire.MemoryAdminResult
	if err = p.c.Call(ctx, "Admin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
