// Code generated by Kitex v0.16.3. DO NOT EDIT.

package management

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ApplicationAuthority(ctx context.Context, accessJSON string, execute bool, callOptions ...callopt.Option) (r *platform.Reply, err error)
	AuthorizeFleet(ctx context.Context, actorID string, tenantID string, ownerID string, execute bool, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Authorize(ctx context.Context, actor *platform.Actor, execute bool, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Peers(ctx context.Context, scopeJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Snapshot(ctx context.Context, scopeJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	ModelProfile(ctx context.Context, scopeJSON string, configJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kManagementClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kManagementClient struct {
	*kClient
}

func (p *kManagementClient) ApplicationAuthority(ctx context.Context, accessJSON string, execute bool, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApplicationAuthority(ctx, accessJSON, execute)
}

func (p *kManagementClient) AuthorizeFleet(ctx context.Context, actorID string, tenantID string, ownerID string, execute bool, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AuthorizeFleet(ctx, actorID, tenantID, ownerID, execute)
}

func (p *kManagementClient) Authorize(ctx context.Context, actor *platform.Actor, execute bool, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Authorize(ctx, actor, execute)
}

func (p *kManagementClient) Peers(ctx context.Context, scopeJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Peers(ctx, scopeJSON)
}

func (p *kManagementClient) Snapshot(ctx context.Context, scopeJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Snapshot(ctx, scopeJSON)
}

func (p *kManagementClient) ModelProfile(ctx context.Context, scopeJSON string, configJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ModelProfile(ctx, scopeJSON, configJSON)
}
