// Code generated by Kitex v0.16.3. DO NOT EDIT.

package management

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AuthorizeUsage": kitex.NewMethodInfo(
		authorizeUsageHandler,
		newManagementAuthorizeUsageArgs,
		newManagementAuthorizeUsageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RecordNotification": kitex.NewMethodInfo(
		recordNotificationHandler,
		newManagementRecordNotificationArgs,
		newManagementRecordNotificationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApplicationAuthority": kitex.NewMethodInfo(
		applicationAuthorityHandler,
		newManagementApplicationAuthorityArgs,
		newManagementApplicationAuthorityResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AuthorizeFleet": kitex.NewMethodInfo(
		authorizeFleetHandler,
		newManagementAuthorizeFleetArgs,
		newManagementAuthorizeFleetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Authorize": kitex.NewMethodInfo(
		authorizeHandler,
		newManagementAuthorizeArgs,
		newManagementAuthorizeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Peers": kitex.NewMethodInfo(
		peersHandler,
		newManagementPeersArgs,
		newManagementPeersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Snapshot": kitex.NewMethodInfo(
		snapshotHandler,
		newManagementSnapshotArgs,
		newManagementSnapshotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ModelProfile": kitex.NewMethodInfo(
		modelProfileHandler,
		newManagementModelProfileArgs,
		newManagementModelProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	managementServiceInfo                = NewServiceInfo()
	managementServiceInfoForClient       = NewServiceInfoForClient()
	managementServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return managementServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return managementServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return managementServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Management"
	handlerType := (*platform.Management)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "platform",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func authorizeUsageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementAuthorizeUsageArgs)
	realResult := result.(*platform.ManagementAuthorizeUsageResult)
	success, err := handler.(platform.Management).AuthorizeUsage(ctx, realArg.ActorID, realArg.TenantID, realArg.OwnerID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementAuthorizeUsageArgs() interface{} {
	return platform.NewManagementAuthorizeUsageArgs()
}

func newManagementAuthorizeUsageResult() interface{} {
	return platform.NewManagementAuthorizeUsageResult()
}

func recordNotificationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementRecordNotificationArgs)
	realResult := result.(*platform.ManagementRecordNotificationResult)
	success, err := handler.(platform.Management).RecordNotification(ctx, realArg.EventJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementRecordNotificationArgs() interface{} {
	return platform.NewManagementRecordNotificationArgs()
}

func newManagementRecordNotificationResult() interface{} {
	return platform.NewManagementRecordNotificationResult()
}

func applicationAuthorityHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementApplicationAuthorityArgs)
	realResult := result.(*platform.ManagementApplicationAuthorityResult)
	success, err := handler.(platform.Management).ApplicationAuthority(ctx, realArg.AccessJSON, realArg.Execute)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementApplicationAuthorityArgs() interface{} {
	return platform.NewManagementApplicationAuthorityArgs()
}

func newManagementApplicationAuthorityResult() interface{} {
	return platform.NewManagementApplicationAuthorityResult()
}

func authorizeFleetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementAuthorizeFleetArgs)
	realResult := result.(*platform.ManagementAuthorizeFleetResult)
	success, err := handler.(platform.Management).AuthorizeFleet(ctx, realArg.ActorID, realArg.TenantID, realArg.OwnerID, realArg.Execute)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementAuthorizeFleetArgs() interface{} {
	return platform.NewManagementAuthorizeFleetArgs()
}

func newManagementAuthorizeFleetResult() interface{} {
	return platform.NewManagementAuthorizeFleetResult()
}

func authorizeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementAuthorizeArgs)
	realResult := result.(*platform.ManagementAuthorizeResult)
	success, err := handler.(platform.Management).Authorize(ctx, realArg.Actor, realArg.Execute)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementAuthorizeArgs() interface{} {
	return platform.NewManagementAuthorizeArgs()
}

func newManagementAuthorizeResult() interface{} {
	return platform.NewManagementAuthorizeResult()
}

func peersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementPeersArgs)
	realResult := result.(*platform.ManagementPeersResult)
	success, err := handler.(platform.Management).Peers(ctx, realArg.ScopeJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementPeersArgs() interface{} {
	return platform.NewManagementPeersArgs()
}

func newManagementPeersResult() interface{} {
	return platform.NewManagementPeersResult()
}

func snapshotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementSnapshotArgs)
	realResult := result.(*platform.ManagementSnapshotResult)
	success, err := handler.(platform.Management).Snapshot(ctx, realArg.ScopeJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementSnapshotArgs() interface{} {
	return platform.NewManagementSnapshotArgs()
}

func newManagementSnapshotResult() interface{} {
	return platform.NewManagementSnapshotResult()
}

func modelProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementModelProfileArgs)
	realResult := result.(*platform.ManagementModelProfileResult)
	success, err := handler.(platform.Management).ModelProfile(ctx, realArg.ScopeJSON, realArg.ConfigJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementModelProfileArgs() interface{} {
	return platform.NewManagementModelProfileArgs()
}

func newManagementModelProfileResult() interface{} {
	return platform.NewManagementModelProfileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AuthorizeUsage(ctx context.Context, actorID string, tenantID string, ownerID string) (r *platform.Reply, err error) {
	var _args platform.ManagementAuthorizeUsageArgs
	_args.ActorID = actorID
	_args.TenantID = tenantID
	_args.OwnerID = ownerID
	var _result platform.ManagementAuthorizeUsageResult
	if err = p.c.Call(ctx, "AuthorizeUsage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RecordNotification(ctx context.Context, eventJSON string) (r *platform.Reply, err error) {
	var _args platform.ManagementRecordNotificationArgs
	_args.EventJSON = eventJSON
	var _result platform.ManagementRecordNotificationResult
	if err = p.c.Call(ctx, "RecordNotification", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApplicationAuthority(ctx context.Context, accessJSON string, execute bool) (r *platform.Reply, err error) {
	var _args platform.ManagementApplicationAuthorityArgs
	_args.AccessJSON = accessJSON
	_args.Execute = execute
	var _result platform.ManagementApplicationAuthorityResult
	if err = p.c.Call(ctx, "ApplicationAuthority", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AuthorizeFleet(ctx context.Context, actorID string, tenantID string, ownerID string, execute bool) (r *platform.Reply, err error) {
	var _args platform.ManagementAuthorizeFleetArgs
	_args.ActorID = actorID
	_args.TenantID = tenantID
	_args.OwnerID = ownerID
	_args.Execute = execute
	var _result platform.ManagementAuthorizeFleetResult
	if err = p.c.Call(ctx, "AuthorizeFleet", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Authorize(ctx context.Context, actor *platform.Actor, execute bool) (r *platform.Reply, err error) {
	var _args platform.ManagementAuthorizeArgs
	_args.Actor = actor
	_args.Execute = execute
	var _result platform.ManagementAuthorizeResult
	if err = p.c.Call(ctx, "Authorize", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Peers(ctx context.Context, scopeJSON string) (r *platform.Reply, err error) {
	var _args platform.ManagementPeersArgs
	_args.ScopeJSON = scopeJSON
	var _result platform.ManagementPeersResult
	if err = p.c.Call(ctx, "Peers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Snapshot(ctx context.Context, scopeJSON string) (r *platform.Reply, err error) {
	var _args platform.ManagementSnapshotArgs
	_args.ScopeJSON = scopeJSON
	var _result platform.ManagementSnapshotResult
	if err = p.c.Call(ctx, "Snapshot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ModelProfile(ctx context.Context, scopeJSON string, configJSON string) (r *platform.Reply, err error) {
	var _args platform.ManagementModelProfileArgs
	_args.ScopeJSON = scopeJSON
	_args.ConfigJSON = configJSON
	var _result platform.ManagementModelProfileResult
	if err = p.c.Call(ctx, "ModelProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
