// Code generated by Kitex v0.16.3. DO NOT EDIT.

package management

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Authorize": kitex.NewMethodInfo(
		authorizeHandler,
		newManagementAuthorizeArgs,
		newManagementAuthorizeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Snapshot": kitex.NewMethodInfo(
		snapshotHandler,
		newManagementSnapshotArgs,
		newManagementSnapshotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ModelProfile": kitex.NewMethodInfo(
		modelProfileHandler,
		newManagementModelProfileArgs,
		newManagementModelProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	managementServiceInfo                = NewServiceInfo()
	managementServiceInfoForClient       = NewServiceInfoForClient()
	managementServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return managementServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return managementServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return managementServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Management"
	handlerType := (*platform.Management)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "platform",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func authorizeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementAuthorizeArgs)
	realResult := result.(*platform.ManagementAuthorizeResult)
	success, err := handler.(platform.Management).Authorize(ctx, realArg.Actor, realArg.Execute)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementAuthorizeArgs() interface{} {
	return platform.NewManagementAuthorizeArgs()
}

func newManagementAuthorizeResult() interface{} {
	return platform.NewManagementAuthorizeResult()
}

func snapshotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementSnapshotArgs)
	realResult := result.(*platform.ManagementSnapshotResult)
	success, err := handler.(platform.Management).Snapshot(ctx, realArg.ScopeJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementSnapshotArgs() interface{} {
	return platform.NewManagementSnapshotArgs()
}

func newManagementSnapshotResult() interface{} {
	return platform.NewManagementSnapshotResult()
}

func modelProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*platform.ManagementModelProfileArgs)
	realResult := result.(*platform.ManagementModelProfileResult)
	success, err := handler.(platform.Management).ModelProfile(ctx, realArg.ScopeJSON, realArg.ConfigJSON)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newManagementModelProfileArgs() interface{} {
	return platform.NewManagementModelProfileArgs()
}

func newManagementModelProfileResult() interface{} {
	return platform.NewManagementModelProfileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Authorize(ctx context.Context, actor *platform.Actor, execute bool) (r *platform.Reply, err error) {
	var _args platform.ManagementAuthorizeArgs
	_args.Actor = actor
	_args.Execute = execute
	var _result platform.ManagementAuthorizeResult
	if err = p.c.Call(ctx, "Authorize", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Snapshot(ctx context.Context, scopeJSON string) (r *platform.Reply, err error) {
	var _args platform.ManagementSnapshotArgs
	_args.ScopeJSON = scopeJSON
	var _result platform.ManagementSnapshotResult
	if err = p.c.Call(ctx, "Snapshot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ModelProfile(ctx context.Context, scopeJSON string, configJSON string) (r *platform.Reply, err error) {
	var _args platform.ManagementModelProfileArgs
	_args.ScopeJSON = scopeJSON
	_args.ConfigJSON = configJSON
	var _result platform.ManagementModelProfileResult
	if err = p.c.Call(ctx, "ModelProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
