// Code generated by Kitex v0.16.3. DO NOT EDIT.
package management

import (
	server "github.com/cloudwego/kitex/server"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler platform.Management, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler platform.Management, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
