// Code generated by Kitex v0.16.3. DO NOT EDIT.

package execution

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Health(ctx context.Context, callOptions ...callopt.Option) (r *platform.Reply, err error)
	CancelPreparedOperation(ctx context.Context, actor *platform.Actor, environmentID string, requestID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	CancelPreparedTransfer(ctx context.Context, actor *platform.Actor, requestID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	BeginTransfer(ctx context.Context, actor *platform.Actor, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	BeginTransferFenced(ctx context.Context, actor *platform.Actor, requestJSON string, fenceJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Transfer(ctx context.Context, actor *platform.Actor, transferID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	ListTransfers(ctx context.Context, actor *platform.Actor, after string, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	CancelTransfer(ctx context.Context, actor *platform.Actor, transferID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	ExtendTransfer(ctx context.Context, actor *platform.Actor, transferID string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error)
	BeginArtifact(ctx context.Context, actor *platform.Actor, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	WriteArtifact(ctx context.Context, actor *platform.Actor, artifactID string, chunkJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	CommitArtifact(ctx context.Context, actor *platform.Actor, artifactID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Artifact(ctx context.Context, actor *platform.Actor, artifactID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Artifacts(ctx context.Context, actor *platform.Actor, after string, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	ReadArtifact(ctx context.Context, actor *platform.Actor, artifactID string, offset int64, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	DeleteArtifact(ctx context.Context, actor *platform.Actor, artifactID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Events(ctx context.Context, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	AcknowledgeEvents(ctx context.Context, eventIDs []string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	AcknowledgeOutput(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, cursor int64, callOptions ...callopt.Option) (r *platform.Reply, err error)
	PreviewPair(ctx context.Context, actorID string, tenantID string, pairID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	ApprovePair(ctx context.Context, actorID string, tenantID string, pairID string, grantsJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Devices(ctx context.Context, actorID string, tenantID string, ownerID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Restrict(ctx context.Context, actorID string, tenantID string, environmentID string, version int64, grantsJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Revoke(ctx context.Context, actorID string, tenantID string, environmentID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Environments(ctx context.Context, actor *platform.Actor, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Submit(ctx context.Context, actor *platform.Actor, environmentID string, requestJSON string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error)
	SubmitFenced(ctx context.Context, actor *platform.Actor, environmentID string, requestJSON string, waitMillis int64, fenceJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Operation(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, cursor int64, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Cancel(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Extend(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kExecutionClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kExecutionClient struct {
	*kClient
}

func (p *kExecutionClient) Health(ctx context.Context, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx)
}

func (p *kExecutionClient) CancelPreparedOperation(ctx context.Context, actor *platform.Actor, environmentID string, requestID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelPreparedOperation(ctx, actor, environmentID, requestID)
}

func (p *kExecutionClient) CancelPreparedTransfer(ctx context.Context, actor *platform.Actor, requestID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelPreparedTransfer(ctx, actor, requestID)
}

func (p *kExecutionClient) BeginTransfer(ctx context.Context, actor *platform.Actor, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BeginTransfer(ctx, actor, requestJSON)
}

func (p *kExecutionClient) BeginTransferFenced(ctx context.Context, actor *platform.Actor, requestJSON string, fenceJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BeginTransferFenced(ctx, actor, requestJSON, fenceJSON)
}

func (p *kExecutionClient) Transfer(ctx context.Context, actor *platform.Actor, transferID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Transfer(ctx, actor, transferID)
}

func (p *kExecutionClient) ListTransfers(ctx context.Context, actor *platform.Actor, after string, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTransfers(ctx, actor, after, limit)
}

func (p *kExecutionClient) CancelTransfer(ctx context.Context, actor *platform.Actor, transferID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelTransfer(ctx, actor, transferID)
}

func (p *kExecutionClient) ExtendTransfer(ctx context.Context, actor *platform.Actor, transferID string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ExtendTransfer(ctx, actor, transferID, waitMillis)
}

func (p *kExecutionClient) BeginArtifact(ctx context.Context, actor *platform.Actor, requestJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BeginArtifact(ctx, actor, requestJSON)
}

func (p *kExecutionClient) WriteArtifact(ctx context.Context, actor *platform.Actor, artifactID string, chunkJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.WriteArtifact(ctx, actor, artifactID, chunkJSON)
}

func (p *kExecutionClient) CommitArtifact(ctx context.Context, actor *platform.Actor, artifactID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommitArtifact(ctx, actor, artifactID)
}

func (p *kExecutionClient) Artifact(ctx context.Context, actor *platform.Actor, artifactID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Artifact(ctx, actor, artifactID)
}

func (p *kExecutionClient) Artifacts(ctx context.Context, actor *platform.Actor, after string, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Artifacts(ctx, actor, after, limit)
}

func (p *kExecutionClient) ReadArtifact(ctx context.Context, actor *platform.Actor, artifactID string, offset int64, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReadArtifact(ctx, actor, artifactID, offset, limit)
}

func (p *kExecutionClient) DeleteArtifact(ctx context.Context, actor *platform.Actor, artifactID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteArtifact(ctx, actor, artifactID)
}

func (p *kExecutionClient) Events(ctx context.Context, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Events(ctx, limit)
}

func (p *kExecutionClient) AcknowledgeEvents(ctx context.Context, eventIDs []string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AcknowledgeEvents(ctx, eventIDs)
}

func (p *kExecutionClient) AcknowledgeOutput(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, cursor int64, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AcknowledgeOutput(ctx, actor, environmentID, operationID, cursor)
}

func (p *kExecutionClient) PreviewPair(ctx context.Context, actorID string, tenantID string, pairID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreviewPair(ctx, actorID, tenantID, pairID)
}

func (p *kExecutionClient) ApprovePair(ctx context.Context, actorID string, tenantID string, pairID string, grantsJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApprovePair(ctx, actorID, tenantID, pairID, grantsJSON)
}

func (p *kExecutionClient) Devices(ctx context.Context, actorID string, tenantID string, ownerID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Devices(ctx, actorID, tenantID, ownerID)
}

func (p *kExecutionClient) Restrict(ctx context.Context, actorID string, tenantID string, environmentID string, version int64, grantsJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Restrict(ctx, actorID, tenantID, environmentID, version, grantsJSON)
}

func (p *kExecutionClient) Revoke(ctx context.Context, actorID string, tenantID string, environmentID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Revoke(ctx, actorID, tenantID, environmentID)
}

func (p *kExecutionClient) Environments(ctx context.Context, actor *platform.Actor, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Environments(ctx, actor)
}

func (p *kExecutionClient) Submit(ctx context.Context, actor *platform.Actor, environmentID string, requestJSON string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Submit(ctx, actor, environmentID, requestJSON, waitMillis)
}

func (p *kExecutionClient) SubmitFenced(ctx context.Context, actor *platform.Actor, environmentID string, requestJSON string, waitMillis int64, fenceJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SubmitFenced(ctx, actor, environmentID, requestJSON, waitMillis, fenceJSON)
}

func (p *kExecutionClient) Operation(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, cursor int64, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Operation(ctx, actor, environmentID, operationID, cursor, limit)
}

func (p *kExecutionClient) Cancel(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Cancel(ctx, actor, environmentID, operationID)
}

func (p *kExecutionClient) Extend(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Extend(ctx, actor, environmentID, operationID, waitMillis)
}
