// Code generated by Kitex v0.16.3. DO NOT EDIT.

package execution

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	platform "github.com/juex-ai/juex/internal/foundation/platformrpc/wire/platform"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Health(ctx context.Context, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Events(ctx context.Context, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	AcknowledgeEvents(ctx context.Context, eventIDs []string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	PreviewPair(ctx context.Context, actorID string, tenantID string, pairID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	ApprovePair(ctx context.Context, actorID string, tenantID string, pairID string, grantsJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Devices(ctx context.Context, actorID string, tenantID string, ownerID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Restrict(ctx context.Context, actorID string, tenantID string, environmentID string, version int64, grantsJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Revoke(ctx context.Context, actorID string, tenantID string, environmentID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Environments(ctx context.Context, actor *platform.Actor, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Submit(ctx context.Context, actor *platform.Actor, environmentID string, requestJSON string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error)
	SubmitFenced(ctx context.Context, actor *platform.Actor, environmentID string, requestJSON string, waitMillis int64, fenceJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Operation(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, cursor int64, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Cancel(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, callOptions ...callopt.Option) (r *platform.Reply, err error)
	Extend(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kExecutionClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kExecutionClient struct {
	*kClient
}

func (p *kExecutionClient) Health(ctx context.Context, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx)
}

func (p *kExecutionClient) Events(ctx context.Context, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Events(ctx, limit)
}

func (p *kExecutionClient) AcknowledgeEvents(ctx context.Context, eventIDs []string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AcknowledgeEvents(ctx, eventIDs)
}

func (p *kExecutionClient) PreviewPair(ctx context.Context, actorID string, tenantID string, pairID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreviewPair(ctx, actorID, tenantID, pairID)
}

func (p *kExecutionClient) ApprovePair(ctx context.Context, actorID string, tenantID string, pairID string, grantsJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApprovePair(ctx, actorID, tenantID, pairID, grantsJSON)
}

func (p *kExecutionClient) Devices(ctx context.Context, actorID string, tenantID string, ownerID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Devices(ctx, actorID, tenantID, ownerID)
}

func (p *kExecutionClient) Restrict(ctx context.Context, actorID string, tenantID string, environmentID string, version int64, grantsJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Restrict(ctx, actorID, tenantID, environmentID, version, grantsJSON)
}

func (p *kExecutionClient) Revoke(ctx context.Context, actorID string, tenantID string, environmentID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Revoke(ctx, actorID, tenantID, environmentID)
}

func (p *kExecutionClient) Environments(ctx context.Context, actor *platform.Actor, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Environments(ctx, actor)
}

func (p *kExecutionClient) Submit(ctx context.Context, actor *platform.Actor, environmentID string, requestJSON string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Submit(ctx, actor, environmentID, requestJSON, waitMillis)
}

func (p *kExecutionClient) SubmitFenced(ctx context.Context, actor *platform.Actor, environmentID string, requestJSON string, waitMillis int64, fenceJSON string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SubmitFenced(ctx, actor, environmentID, requestJSON, waitMillis, fenceJSON)
}

func (p *kExecutionClient) Operation(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, cursor int64, limit int32, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Operation(ctx, actor, environmentID, operationID, cursor, limit)
}

func (p *kExecutionClient) Cancel(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Cancel(ctx, actor, environmentID, operationID)
}

func (p *kExecutionClient) Extend(ctx context.Context, actor *platform.Actor, environmentID string, operationID string, waitMillis int64, callOptions ...callopt.Option) (r *platform.Reply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Extend(ctx, actor, environmentID, operationID, waitMillis)
}
