// Code generated by go run ./scripts/gen-management-schema. DO NOT EDIT.

export type Role = "admin" | "member";
export type MembershipStatus = "active" | "suspended" | "removed";

export interface Agent {
  agent_management?: boolean;
  dynamic_instructions: DynamicInstructions;
  configuration: Configuration;
  workspace_configuration: WorkspaceConfiguration | null;
  extensions: Array<Binding>;
  hooks: Array<Declaration>;
  purging: boolean;
  worker_depth: number;
  id: string;
  fleet_id: string;
  name: string;
  instructions: string;
  status: string;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface AgentConfig {
  dynamic_instructions?: DynamicInstructions | null;
  configuration?: Configuration | null;
  hooks?: Array<Declaration>;
  worker_depth?: number;
  name: string;
  instructions: string;
}

export interface AgentDetail {
  agent: Agent;
  owner_id: string;
  can_execute: boolean;
  layers: ConfigurationLayers;
  effective: EffectiveConfiguration;
}

export interface AgentLifecycleChange {
  request_id: string;
  action: string;
  version: number;
  interrupt: boolean;
}

export interface AgentLifecycleReceipt {
  request_id: string;
  action: string;
  outcome: string;
  state: AgentRunState;
}

export interface AgentManagementRequest {
  version: number;
  enabled: boolean;
}

export interface AgentRunState {
  initialized: boolean;
  agent_id: string;
  mode: string;
  version: number;
  activation_epoch: number;
  busy: Array<string>;
}

export interface ArchiveAgentRequest {
  version: number;
  archived: boolean;
}

export interface ArchiveThreadRequest {
  archived: boolean;
}

export interface Artifact {
  id: string;
  scope: Scope;
  request: ArtifactRequest;
  state: string;
  created_at: string;
}

export interface ArtifactRequest {
  request_id: string;
  name: string;
  media_type: string;
  visibility: string;
  manifest: FileManifest;
  source?: ArtifactSource | null;
}

export interface ArtifactSource {
  environment_id: string;
  authorization_version: number;
  operation_id: string;
  path: string;
  working_directory?: string;
}

export interface ArtifactUpload {
  artifact: Artifact;
  cursor: number;
}

export interface Binding {
  id: string;
  enabled: boolean;
  environment_id: string;
  authorization_version: number;
  directory: string;
  inspection_id: string;
  resources: Array<string>;
  catalog: Catalog;
}

export interface Block {
  type: string;
  text?: string;
  media?: MediaRef | null;
  tool_use_id?: string;
  tool_name?: string;
  input?: Record<string, unknown>;
  timeout_seconds?: number;
  content?: string;
  is_error?: boolean;
  signature?: string;
  redacted?: boolean;
  artifact?: ContextArtifactProjection | null;
  result_fact?: ResultFact | null;
}

export interface CalendarChange {
  request_id: string;
  id: string;
  version: number;
  action: string;
  definition?: CalendarDefinition | null;
  occurrence_id?: string;
}

export interface CalendarConfiguration {
  version: number;
  enabled: boolean;
}

export interface CalendarDefinition {
  name: string;
  content: string;
  mode: string;
  agent_id?: string;
  rule: CalendarRule;
  catch_up?: string;
  max_lateness_minutes: number;
}

export interface CalendarLunarOptions {
  leap_month?: string;
}

export interface CalendarOccurrence {
  purged: boolean;
  external_pending: boolean;
  cancel_requested: boolean;
  id: string;
  schedule_id: string;
  schedule_version: number;
  name: string;
  content: string;
  mode: string;
  agent_id?: string;
  rule: CalendarRule;
  catch_up?: string;
  max_lateness_minutes: number;
  scheduled_at: string;
  state: string;
  main_thread_id?: string;
  input_id?: string;
  worker_id?: string;
  operations?: Array<string>;
  updated_at: string;
}

export interface CalendarOccurrencePage {
  occurrences: Array<CalendarOccurrence>;
  next: number;
}

export interface CalendarReceipt {
  schedule_id: string;
  version: number;
  state: string;
  occurrence_id?: string;
}

export interface CalendarRule {
  frequency: string;
  timezone?: string;
  at?: string;
  year?: number;
  month?: number;
  day?: number;
  time?: string;
  months?: Array<number>;
  days?: Array<number>;
  times?: Array<string>;
  weekdays?: Array<string>;
  every_seconds?: number;
  lunar?: CalendarLunarOptions | null;
}

export interface CalendarSchedule {
  id: string;
  name: string;
  content: string;
  mode: string;
  agent_id?: string;
  rule: CalendarRule;
  catch_up?: string;
  max_lateness_minutes: number;
  version: number;
  status: string;
  pause_reason?: string;
  next_at?: string;
  updated_at: string;
}

export interface CalendarSchedulePage {
  schedules: Array<CalendarSchedule>;
  next: number;
}

export interface CalendarStatus {
  enabled: boolean;
  epoch: number;
  version: number;
  schedules: number;
  pending: number;
}

export interface Catalog {
  manifest: Manifest;
  skills: Array<SkillContent>;
  revision: string;
  source_kind?: string;
  skipped?: Array<SkippedSource>;
}

export interface CompactionMetadata {
  auto: boolean;
  reason: string;
  previous_summary_id?: string;
  first_kept_message_id?: string;
  tail_start_message_id?: string;
  retained_message_ids?: Array<string>;
  retained_input_references?: Array<Message>;
  tokens_before: number;
  tokens_after: number;
  summary_chars: number;
  summary_model?: string;
}

export interface CompactionRequest {
  request_id: string;
  focus: string;
}

export interface Configuration {
  module_preset?: string;
  models?: Array<string>;
  modules?: Record<string, boolean>;
}

export interface ConfigurationLayer {
  version: number;
  declaration: Configuration;
}

export interface ConfigurationLayers {
  tenant: ConfigurationLayer;
  fleet: ConfigurationLayer;
  workspace: ConfigurationLayer;
  agent: ConfigurationLayer;
}

export interface ConfigurationSource {
  layer: string;
  version: number;
  derived_from?: string;
  preset?: string;
}

export interface ConfigureAgentRequest {
  dynamic_instructions?: DynamicInstructions | null;
  configuration?: Configuration | null;
  hooks?: Array<Declaration>;
  worker_depth?: number;
  name: string;
  instructions: string;
  version: number;
}

export interface ContextArtifactProjection {
  source_kind: string;
  message_id?: string;
  tool_use_id?: string;
  tool_name?: string;
  original_bytes: number;
  stored_path: string;
  sha256: string;
  head_bytes: number;
  tail_bytes: number;
  truncated: boolean;
}

export interface ContextUsagePart {
  key: string;
  label: string;
  tokens: number;
}

export interface Declaration {
  authorization_version?: number;
  extension?: ExtensionContext | null;
  environment?: Record<string, string>;
  id: string;
  enabled: boolean;
  events: Array<string>;
  tools?: Array<string>;
  environment_id?: string;
  command: Array<string>;
  working_directory?: string;
  timeout_seconds?: number;
  max_output_bytes?: number;
  required: boolean;
  source?: string;
}

export interface DefaultEnvironment {
  environment_id: string;
  working_directory: string;
  version: number;
}

export interface Device {
  default: boolean;
  id: string;
  journal_id: string;
  name: string;
  kind: string;
  os: string;
  online: boolean;
  capabilities: Array<string>;
  working_directory: string;
  working_files_root?: string;
  permission_mode: string;
  authorization_version: number;
  availability?: string;
  error?: string;
  managed: boolean;
  tenant_id: string;
  user_id: string;
  fleet_id: string;
  removal_epoch: number;
  status: string;
  version: number;
  grants: Record<string, Array<string>>;
  ceiling: Record<string, Array<string>>;
  last_seen: string | null;
  connection_epoch: number;
}

export interface DynamicInstructions {
  enabled: boolean;
  global_path: string;
}

export interface EffectiveConfiguration {
  models: Array<string>;
  model_source: ConfigurationSource;
  modules: Record<string, EffectiveModule>;
}

export interface EffectiveModule {
  enabled: boolean;
  source: ConfigurationSource;
}

export interface Environment {
  default: boolean;
  id: string;
  journal_id: string;
  name: string;
  kind: string;
  os: string;
  online: boolean;
  capabilities: Array<string>;
  working_directory: string;
  working_files_root?: string;
  permission_mode: string;
  authorization_version: number;
  availability?: string;
  error?: string;
}

export interface EnvironmentInspection {
  binding: DefaultEnvironment;
  default_state: string;
  environments: Array<EnvironmentStatus>;
  observed_at: string;
}

export interface EnvironmentStatus {
  default: boolean;
  id: string;
  journal_id: string;
  name: string;
  kind: string;
  os: string;
  online: boolean;
  capabilities: Array<string>;
  working_directory: string;
  working_files_root?: string;
  permission_mode: string;
  authorization_version: number;
  availability?: string;
  error?: string;
  managed: boolean;
  last_seen: string | null;
}

export interface Event {
  observation_ids?: Array<string>;
  tool_attempt_id?: string;
  turn_id?: string;
  id: string;
  thread_id: string;
  sequence: number;
  generation: number;
  kind: string;
  data: unknown;
  created_at: string;
}

export interface ExtendTransferRequest {
  wait_hours: number;
}

export interface ExtensionChange {
  version: number;
  enabled: boolean;
  remove?: boolean;
  inspection_id?: string;
  environment_id?: string;
  resources: Array<string>;
}

export interface ExtensionContext {
  binding_id: string;
  directory: string;
}

export interface ExtensionInspection {
  source_kind?: string;
  operation_id: string;
  environment_id: string;
  authorization_version: number;
  directory: string;
  state: string;
  error?: string;
  catalog?: Catalog | null;
}

export interface ExtensionInspectionRequest {
  source_kind?: string;
  request_id: string;
  environment_id: string;
  directory: string;
}

export interface FileChunk {
  offset: number;
  data: string;
  sha256: string;
}

export interface FileLocation {
  environment_id: string;
  authorization_version: number;
  path: string;
  working_directory?: string;
}

export interface FileManifest {
  size: number;
  sha256: string;
}

export interface Fleet {
  id: string;
  tenant_id: string;
  user_id: string;
}

export interface FleetOverview {
  id: string;
  tenant_id: string;
  user_id: string;
  purged: boolean;
  purging: boolean;
  tenant_settings: ConfigurationLayer;
  owner: User;
  membership: Membership;
  settings: FleetSettings;
  agents: Array<Agent>;
}

export interface FleetSettings {
  configuration: Configuration;
  version: number;
}

export interface InputCheck {
  input_id: string;
  scope_id: string;
  message_id?: string;
  accepted_order: number;
  delivery: string;
  checked_at?: string | null;
  check_action_id?: string;
  check_message_id?: string;
  tool_use_id?: string;
}

export interface InputCheckPage {
  enabled: boolean;
  scope_id: string;
  items: Array<InputCheck>;
}

export interface InputCheckQuery {
  message_ids: Array<string>;
}

export interface InputChecklist {
  enabled: boolean;
  scope_id: string;
  items: Array<InputCheck>;
}

export interface InputImage {
  artifact_id: string;
  sha256: string;
  media_type: string;
  size: number;
}

export interface InputReceipt {
  id: string;
  request_id: string;
  thread_id: string;
  state: string;
  accepted_at: string;
}

export interface InputRequest {
  request_id: string;
  thread_id: string;
  text: string;
  images?: Array<InputImage>;
}

export interface InvitationPreview {
  id: string;
  tenant_id: string;
  email: string;
  role: Role;
  expires_at: string;
  tenant_name: string;
  requires_login: boolean;
}

export interface InvitationView {
  id: string;
  tenant_id: string;
  email: string;
  role: Role;
  expires_at: string;
  link: string;
  delivery_status: string;
}

export interface MCPConnection {
  transport: string;
  connected_at: string;
  server_name: string;
  server_version: string;
  protocol_version: string;
}

export interface MCPPage {
  items: Array<MCPStatus>;
  next: string;
  observed_at: string;
}

export interface MCPRefresh {
  id: string;
  cursor: string;
}

export interface MCPResource {
  id: string;
  description?: string;
  command: Array<string>;
  environment?: Record<string, string>;
  transport?: string;
  url?: string;
  headers?: Record<string, string>;
}

export interface MCPStatus {
  id: string;
  environment_id: string;
  environment: string;
  state: string;
  observed_state: string;
  created_at: string;
  can_refresh: boolean;
  binding_id: string;
  directory: string;
  handshake: MCPConnection | null;
  latest_tools: MCPToolList | null;
}

export interface MCPTool {
  name: string;
  description: string;
  input_schema: unknown;
}

export interface MCPToolList {
  id: string;
  state: string;
  requested_at: string;
  cursor: string;
  next_cursor: string;
  tools: Array<MCPTool>;
  output_expired: boolean;
  incomplete: boolean;
}

export interface Manifest {
  manifest_version: number;
  name: string;
  version: string;
  description?: string;
  environment?: Record<string, string>;
  skills: Array<SkillResource>;
  hooks: Array<Declaration>;
  mcp: Array<MCPResource>;
  observables: Array<ObservableResource>;
}

export interface MediaRef {
  artifact_id?: string;
  artifact_path?: string;
  media_type?: string;
  sha256?: string;
  original_bytes?: number;
  width?: number;
  height?: number;
}

export interface MemberView {
  id: string;
  email: string;
  email_verified: boolean;
  tenant_id: string;
  user_id: string;
  role: Role;
  status: MembershipStatus;
  version: number;
  fleet_id: string;
}

export interface Membership {
  tenant_id: string;
  user_id: string;
  role: Role;
  status: MembershipStatus;
  version: number;
}

export interface MemoryAdminRequest {
  key: string;
  action: string;
  changes?: Array<MemoryChange>;
  sources?: Array<MemorySource>;
  entry_ids?: Array<string>;
}

export interface MemoryChange {
  entry: MemoryEntry;
  expected_revision: number;
  delete?: boolean;
}

export interface MemoryConfiguration {
  version: number;
  enabled: boolean;
  strategy: string;
}

export interface MemoryDomain {
  id: string;
  name: string;
  description: string;
  relations?: Array<MemoryRelation>;
  policy: string;
}

export interface MemoryEntity {
  id: string;
  name: string;
  kind: string;
}

export interface MemoryEntry {
  id: string;
  revision: number;
  name: string;
  summary: string;
  type: string;
  scope: MemoryScope;
  body: string;
  sources: Array<MemorySource>;
  entities?: Array<MemoryEntity>;
  facts?: Array<MemoryFact>;
  created_at: string;
  updated_at: string;
}

export interface MemoryFact {
  id: string;
  domain: string;
  qualifiers?: Record<string, string>;
  reason: string;
  replaces?: Array<string>;
  due_at?: string | null;
  time_note?: string;
  subject: string;
  predicate: string;
  value?: string;
  object?: string;
  status: string;
  source_type: string;
  sources: Array<MemorySource>;
  recorded_at: string;
  valid_from?: string | null;
  valid_until?: string | null;
}

export interface MemoryFactPage {
  facts: Array<MemoryFactView>;
  next: number;
  total: number;
  domain_total: number;
  fence: number;
}

export interface MemoryFactView {
  entry_id: string;
  revision: number;
  scope: MemoryScope;
  fact: MemoryFact;
  subject: MemoryEntity;
  object?: MemoryEntity | null;
  lifecycle: string;
}

export interface MemoryPage {
  entries: Array<MemoryEntry>;
  next: number;
  fence: number;
}

export interface MemoryRelation {
  optional_qualifiers?: Array<string>;
  source_types: Array<string>;
  predicate: string;
  description: string;
  subjects: Array<string>;
  objects?: Array<string>;
  value_type?: string;
  qualifiers?: Array<string>;
  cardinality: string;
  competition: Array<string>;
  temporal: string;
  updates: Array<string>;
  evidence: string;
  positive: string;
  negative: string;
}

export interface MemoryReviewPage {
  reviews: Array<MemoryReviewSummary>;
  next: number;
}

export interface MemoryReviewSummary {
  id: string;
  state: string;
  reason?: string;
  committed: boolean;
  index_ready: boolean;
  entry_ids?: Array<string>;
  attempts: number;
  updated_at: string;
  agent_id: string;
  thread_id: string;
  worker_id?: string;
}

export interface MemoryScope {
  workspace?: string;
  project?: string;
}

export interface MemorySource {
  fleet_id: string;
  agent_id: string;
  thread_id: string;
  generation_id: string;
  from: number;
  through: number;
}

export interface MemoryStatus {
  enabled: boolean;
  epoch: number;
  version: number;
  strategy: string;
  fence: number;
  entries: number;
  pending: number;
}

export interface MemoryStorageRules {
  entries: Array<string>;
  sources: Array<MemorySource>;
  next: number;
}

export interface Message {
  id?: string;
  role: string;
  blocks: Array<Block>;
  kind?: string;
  policy_blocked?: boolean;
  model?: string;
  compaction?: CompactionMetadata | null;
}

export interface Model {
  id: string;
  provider: string;
  name: string;
  protocol: string;
  context_window: number;
  max_output: number;
  output_reserve: number;
  enabled: boolean;
}

export interface ModelProgress {
  attempt_id: string;
  turn_id: string;
  generation: number;
  sequence: number;
  model: string;
  state: string;
  started_at: string;
  updated_at: string;
  snapshot: ProgressSnapshot;
}

export interface Notification {
  id: string;
  sequence: number;
  application: string;
  resource_id: string;
  agent_id?: string;
  kind: string;
  title: string;
  summary: string;
  created_at: string;
  read: boolean;
}

export interface NotificationPage {
  items: Array<Notification>;
  next: number;
  unread: number;
}

export interface NotificationPreferences {
  version: number;
  completions: boolean;
  email: boolean;
}

export interface NotificationReadRequest {
  read: boolean;
}

export interface ObservableBatch {
  interval_seconds?: number;
  max_chars?: number;
}

export interface ObservableFilter {
  contains?: string;
  regex?: string;
  kind?: string;
  severity?: string;
}

export interface ObservableOptions {
  streams?: Array<string>;
  parser: ObservableParser;
  filters?: Array<ObservableFilter>;
  batch: ObservableBatch;
  on_exit?: string;
  kind?: string;
  severity?: string;
}

export interface ObservableParser {
  type: string;
  content_field?: string;
  kind_field?: string;
  severity_field?: string;
  time_field?: string;
  attachments_field?: string;
}

export interface ObservableResource {
  id: string;
  description?: string;
  command: Array<string>;
  environment?: Record<string, string>;
  options: ObservableOptions;
}

export interface ObservationContent {
  id: string;
  kind: string;
  environment_id: string;
  operation_id?: string;
  created_at: string;
  data: string;
  offset: number;
  next_offset: number;
  total_characters: number;
  has_more: boolean;
}

export interface ObservationPage {
  targets: Array<ObserverTarget>;
  targets_truncated: boolean;
  sources: Array<ObservationStatus>;
  controls: Array<ObserverControl>;
  next: string;
}

export interface ObservationStatus {
  subscriptions_truncated: boolean;
  id: string;
  thread_id: string;
  origin: string;
  control_id: string;
  environment_id: string;
  operation_id: string;
  kind: string;
  directory: string;
  cursor: number;
  closed: boolean;
  stop_requested: boolean;
  subscriptions: Array<Subscription>;
}

export interface ObservedEvent {
  id: string;
  kind: string;
  environment_id: string;
  operation_id?: string;
  offset?: number;
  data: unknown;
  created_at: string;
  data_truncated: boolean;
  pending: number;
  delivered: number;
  skipped: number;
}

export interface ObservedEvents {
  items: Array<ObservedEvent>;
  next: string;
}

export interface ObserverControl {
  request_id: string;
  id: string;
  thread_id: string;
  binding_id: string;
  resource_id: string;
  kind: string;
  revision: string;
  mode: string;
  desired: string;
  source_id: string;
  state: string;
  attempt: number;
  created_at: string;
}

export interface ObserverStart {
  request_id: string;
  thread_id: string;
  binding_id: string;
  resource_id: string;
  kind: string;
  agent_version: number;
  revision: string;
  mode: string;
  subscribe: boolean;
}

export interface ObserverTarget {
  id: string;
  name: string;
}

export interface OperationOutput {
  id: string;
  environment_id: string;
  state: string;
  output: string;
  next_cursor: number;
  output_bytes: number;
  truncated: boolean;
  output_expired: boolean;
  exit_code: number | null;
  error: string;
}

export interface OwnerScope {
  tenant_id: string;
  user_id: string;
  fleet_id: string;
  actor_id: string;
  actor_authorization_epoch: number;
  membership_execution_epoch: number;
  removal_epoch: number;
  can_execute: boolean;
  owner_email: string;
  tenant_name: string;
}

export interface Pairing {
  id: string;
  environment_id: string;
  name: string;
  os: string;
  working_directory: string;
  capabilities: Array<string>;
  state: string;
  expires_at: string;
  owner: OwnerScope;
  grants: Record<string, Array<string>>;
  agent_epochs: Record<string, number>;
  approval_nonce: string;
}

export interface Policy {
  disabled: Array<string>;
  enabled?: Array<string>;
  version?: number;
  skill_sources?: boolean;
}

export interface ProcessEnvironmentChange {
  version: number;
  set: Record<string, string>;
  remove: Array<string>;
  environment_id?: string;
  working_directory?: string;
}

export interface ProcessEnvironmentLayer {
  version: number;
  keys: Array<string>;
  environment_id?: string;
  working_directory?: string;
}

export interface ProcessEnvironmentVariable {
  name: string;
  source: string;
}

export interface ProcessEnvironmentView {
  layers: Record<string, ProcessEnvironmentLayer>;
  effective: Array<ProcessEnvironmentVariable>;
  tenant_writable: boolean;
}

export interface ProgressBlock {
  kind: string;
  index: number;
  text: string;
}

export interface ProgressSnapshot {
  revision: number;
  blocks: Array<ProgressBlock>;
  truncated: boolean;
}

export interface PurgeJob {
  id: string;
  tenant_id: string;
  user_id: string;
  fleet_id: string;
  agent_ids: Array<string>;
  whole_fleet: boolean;
  actor_id: string;
  version: number;
  state: string;
  step: number;
  receipts: Record<string, Receipt>;
  error: string;
  created_at: string;
  updated_at: string;
}

export interface PurgeRequest {
  id: string;
  agent_id: string;
  version: number;
}

export interface Receipt {
  fenced: boolean;
  data_removed: boolean;
  unconfirmed: number;
  environments_pending: number;
}

export interface RequestInspection {
  attempt_id: string;
  turn_id: string;
  recorded_at: string;
  generation: number;
  purpose: string;
  model: string;
  provider: string;
  context_window: number;
  output_reserve: number;
  estimated_tokens: number;
  breakdown: Array<ContextUsagePart>;
  system: string;
  tools: Array<ToolSpec>;
  message_count: number;
}

export interface ResetContextRequest {
  request_id: string;
}

export interface ResultFact {
  owner: string;
  data?: unknown;
}

export interface RuntimeStatus {
  initialized: boolean;
  main_thread_id: string;
  active_threads: number;
  archived_threads: number;
  pending_inputs: number;
  held_inputs: number;
  states: Record<string, number>;
  last_activity: string | null;
  observed_at: string;
}

export interface Scope {
  tenant_id: string;
  user_id: string;
  fleet_id: string;
  actor_id: string;
  actor_authorization_epoch: number;
  membership_execution_epoch: number;
  removal_epoch: number;
  can_execute: boolean;
  owner_email: string;
  tenant_name: string;
  capabilities: Policy;
  agent_id: string;
  agent_execution_epoch: number;
}

export interface Session {
  user: User;
  expires_at: string;
}

export interface SkillContent {
  id: string;
  content: string;
}

export interface SkillResource {
  id: string;
  description: string;
  path: string;
}

export interface SkippedSource {
  path: string;
  reason: string;
  target?: string;
}

export interface SourceSubscriptionChange {
  enabled: boolean;
}

export interface Subscription {
  id: string;
  thread_id: string;
  kind: string;
  environment_id: string;
  operation_id?: string;
  method?: string;
  generation: number;
  enabled: boolean;
}

export interface TenantAccess {
  id: string;
  name: string;
  role: Role;
  fleet_id: string;
}

export interface Thread {
  application?: string;
  id: string;
  agent_id: string;
  parent_id: string;
  kind: string;
  name: string;
  retention: string;
  state: string;
  generation: number;
  sequence: number;
  pending_inputs: number;
  queued_inputs?: number;
  held_inputs: number;
  created_at: string;
  updated_at: string;
}

export interface ThreadDeletionReceipt {
  thread_id: string;
  deleted: boolean;
}

export interface ThreadInspection {
  input_checklist: InputChecklist;
  working_files: WorkingFiles | null;
  thread: Thread;
  state: ThreadState;
  capabilities: Policy;
  latest_request: RequestInspection | null;
  usage: UsageCounts;
  imported_history: boolean;
}

export interface ThreadNotes {
  content: string;
  updated_at?: string;
}

export interface ThreadState {
  notes: ThreadNotes;
  tasks: Array<ThreadTask>;
  revision: number;
}

export interface ThreadTask {
  id: string;
  title: string;
  description: string;
  acceptance: string;
  status: string;
  status_reason: string;
  priority: string;
  continuation_count: number;
  updated_at: string;
}

export interface Timeline {
  previous_sequence?: number;
  has_previous?: boolean;
  progress: Array<ModelProgress>;
  thread: Thread;
  events: Array<Event>;
  next_sequence: number;
  has_more: boolean;
}

export interface ToolSpec {
  name: string;
  description: string;
  schema: Record<string, unknown>;
}

export interface Transfer {
  id: string;
  scope: Scope;
  request: TransferRequest;
  state: string;
  wait_reason?: string;
  artifact_id: string;
  cancel_requested: boolean;
  error: string;
  wait_until: string;
  created_at: string;
}

export interface TransferRequest {
  request_id: string;
  source?: FileLocation | null;
  target?: FileLocation | null;
  artifact_id?: string;
  name?: string;
  media_type?: string;
  visibility?: string;
}

export interface UsageCounts {
  attempts: number;
  reported: number;
  partial: number;
  unknown: number;
  input_tokens: number;
  output_tokens: number;
  cached_input_tokens: number;
  total_tokens: number;
}

export interface UsagePeriod {
  id: number;
  timezone: string;
  effective_from: string;
  effective_until: string | null;
}

export interface UsageQuery {
  tenant_id: string;
  user_id?: string;
  from: string;
  until: string;
  group: string;
  offset: number;
  limit: number;
}

export interface UsageReport {
  query: UsageQuery;
  totals: UsageCounts;
  periods: Array<UsagePeriod>;
  rows: Array<UsageRow>;
  has_more: boolean;
  detail_days: number;
}

export interface UsageRow {
  attempts: number;
  reported: number;
  partial: number;
  unknown: number;
  input_tokens: number;
  output_tokens: number;
  cached_input_tokens: number;
  total_tokens: number;
  period_id: number;
  bucket: string;
  tenant_id: string;
  user_id: string;
  model_id: string;
  provider: string;
  model: string;
  kind: string;
}

export interface User {
  id: string;
  email: string;
  email_verified: boolean;
}

export interface WorkerRequest {
  request_id: string;
  name: string;
}

export interface WorkingFiles {
  environment_id: string;
  directory: string;
}

export interface WorkspaceConfiguration {
  version: number;
  declaration: Configuration;
  path: string;
  read_started_at: string;
  environment_id: string;
  working_directory: string;
  operation_id: string;
  sha256: string;
  authorization_version: number;
}

export interface WorkspaceConfigurationChange {
  version: number;
  environment_id: string;
  operation_id: string;
  sha256: string;
  remove: boolean;
}

export interface WorkspaceConfigurationPreview {
  receipt: WorkspaceReadReceipt;
  configuration?: WorkspaceConfiguration | null;
  effective?: EffectiveConfiguration | null;
}

export interface WorkspaceEntry {
  path: string;
  name: string;
  kind: string;
  size: number;
  modified_at: string;
}

export interface WorkspaceListing {
  entries: Array<WorkspaceEntry>;
  next_cursor: string;
  scan_limited: boolean;
  preview?: WorkspacePreview | null;
}

export interface WorkspacePreview {
  entry: WorkspaceEntry;
  text: string;
  media_type: string;
  binary: boolean;
  truncated: boolean;
}

export interface WorkspaceQuery {
  path: string;
  search?: string;
  hidden: boolean;
  after?: string;
  read: boolean;
}

export interface WorkspaceReadReceipt {
  authorization_version: number;
  read_started_at: string;
  operation_id: string;
  environment_id: string;
  directory: string;
  query: WorkspaceQuery;
  state: string;
  error: string;
  listing?: WorkspaceListing | null;
}

export interface WorkspaceReadRequest {
  request_id: string;
  environment_id: string;
  directory: string;
  query: WorkspaceQuery;
}
