// Code generated by go run ./scripts/gen-management-schema. DO NOT EDIT.

export type Role = "admin" | "member";
export type MembershipStatus = "active" | "suspended" | "removed";

export interface Agent {
  id: string;
  fleet_id: string;
  name: string;
  instructions: string;
  model_id: string;
  status: string;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface AgentConfig {
  name: string;
  instructions: string;
  model_id: string;
}

export interface AgentDetail {
  agent: Agent;
  owner_id: string;
  can_execute: boolean;
  effective_model_id: string;
}

export interface ArchiveAgentRequest {
  version: number;
  archived: boolean;
}

export interface Artifact {
  id: string;
  scope: Scope;
  request: ArtifactRequest;
  state: string;
  created_at: string;
}

export interface ArtifactRequest {
  request_id: string;
  name: string;
  media_type: string;
  visibility: string;
  manifest: FileManifest;
  source?: ArtifactSource | null;
}

export interface ArtifactSource {
  environment_id: string;
  authorization_version: number;
  operation_id: string;
  path: string;
  working_directory?: string;
}

export interface ArtifactUpload {
  artifact: Artifact;
  cursor: number;
}

export interface Block {
  type: string;
  text?: string;
  media?: MediaRef | null;
  tool_use_id?: string;
  tool_name?: string;
  input?: Record<string, unknown>;
  timeout_seconds?: number;
  content?: string;
  is_error?: boolean;
  signature?: string;
  redacted?: boolean;
  artifact?: ContextArtifactProjection | null;
  result_fact?: ResultFact | null;
}

export interface CompactionMetadata {
  auto: boolean;
  reason: string;
  previous_summary_id?: string;
  first_kept_message_id?: string;
  tail_start_message_id?: string;
  retained_message_ids?: Array<string>;
  retained_input_references?: Array<Message>;
  tokens_before: number;
  tokens_after: number;
  summary_chars: number;
  summary_model?: string;
}

export interface CompactionRequest {
  request_id: string;
  focus: string;
}

export interface ConfigureAgentRequest {
  name: string;
  instructions: string;
  model_id: string;
  version: number;
}

export interface ContextArtifactProjection {
  source_kind: string;
  message_id?: string;
  tool_use_id?: string;
  tool_name?: string;
  original_bytes: number;
  stored_path: string;
  sha256: string;
  head_bytes: number;
  tail_bytes: number;
  truncated: boolean;
}

export interface Device {
  id: string;
  journal_id: string;
  name: string;
  kind: string;
  os: string;
  online: boolean;
  capabilities: Array<string>;
  working_directory: string;
  permission_mode: string;
  authorization_version: number;
  availability?: string;
  error?: string;
  tenant_id: string;
  user_id: string;
  fleet_id: string;
  removal_epoch: number;
  status: string;
  version: number;
  grants: Record<string, Array<string>>;
  ceiling: Record<string, Array<string>>;
  last_seen: string | null;
  connection_epoch: number;
}

export interface Environment {
  id: string;
  journal_id: string;
  name: string;
  kind: string;
  os: string;
  online: boolean;
  capabilities: Array<string>;
  working_directory: string;
  permission_mode: string;
  authorization_version: number;
  availability?: string;
  error?: string;
}

export interface Event {
  id: string;
  thread_id: string;
  sequence: number;
  generation: number;
  kind: string;
  data: unknown;
  created_at: string;
}

export interface ExtendTransferRequest {
  wait_hours: number;
}

export interface FileChunk {
  offset: number;
  data: string;
  sha256: string;
}

export interface FileLocation {
  environment_id: string;
  authorization_version: number;
  path: string;
  working_directory?: string;
}

export interface FileManifest {
  size: number;
  sha256: string;
}

export interface Fleet {
  id: string;
  tenant_id: string;
  user_id: string;
}

export interface FleetOverview {
  id: string;
  tenant_id: string;
  user_id: string;
  platform_default_model_id: string;
  owner: User;
  membership: Membership;
  settings: FleetSettings;
  agents: Array<Agent>;
}

export interface FleetSettings {
  default_model_id: string;
  memory_enabled: boolean;
  calendar_enabled: boolean;
  version: number;
}

export interface InputReceipt {
  id: string;
  request_id: string;
  thread_id: string;
  state: string;
  accepted_at: string;
}

export interface InputRequest {
  request_id: string;
  thread_id: string;
  text: string;
}

export interface InvitationPreview {
  id: string;
  tenant_id: string;
  email: string;
  role: Role;
  expires_at: string;
  tenant_name: string;
  requires_login: boolean;
}

export interface InvitationView {
  id: string;
  tenant_id: string;
  email: string;
  role: Role;
  expires_at: string;
  link: string;
  delivery_status: string;
}

export interface MediaRef {
  artifact_path?: string;
  media_type?: string;
  sha256?: string;
  original_bytes?: number;
  width?: number;
  height?: number;
}

export interface MemberView {
  id: string;
  email: string;
  email_verified: boolean;
  tenant_id: string;
  user_id: string;
  role: Role;
  status: MembershipStatus;
  version: number;
  fleet_id: string;
}

export interface Membership {
  tenant_id: string;
  user_id: string;
  role: Role;
  status: MembershipStatus;
  version: number;
}

export interface Message {
  id?: string;
  role: string;
  blocks: Array<Block>;
  kind?: string;
  policy_blocked?: boolean;
  model?: string;
  compaction?: CompactionMetadata | null;
}

export interface Model {
  id: string;
  provider: string;
  name: string;
  protocol: string;
  context_window: number;
  max_output: number;
  enabled: boolean;
}

export interface OwnerScope {
  tenant_id: string;
  user_id: string;
  fleet_id: string;
  actor_id: string;
  actor_authorization_epoch: number;
  membership_execution_epoch: number;
  removal_epoch: number;
  can_execute: boolean;
  owner_email: string;
  tenant_name: string;
}

export interface Pairing {
  id: string;
  environment_id: string;
  name: string;
  os: string;
  working_directory: string;
  capabilities: Array<string>;
  state: string;
  expires_at: string;
  owner: OwnerScope;
  grants: Record<string, Array<string>>;
  agent_epochs: Record<string, number>;
  approval_nonce: string;
}

export interface ResultFact {
  owner: string;
  data?: unknown;
}

export interface Scope {
  tenant_id: string;
  user_id: string;
  fleet_id: string;
  actor_id: string;
  actor_authorization_epoch: number;
  membership_execution_epoch: number;
  removal_epoch: number;
  can_execute: boolean;
  owner_email: string;
  tenant_name: string;
  agent_id: string;
  agent_execution_epoch: number;
}

export interface Session {
  user: User;
  expires_at: string;
}

export interface TenantAccess {
  id: string;
  name: string;
  role: Role;
  fleet_id: string;
}

export interface Thread {
  id: string;
  agent_id: string;
  parent_id: string;
  kind: string;
  name: string;
  retention: string;
  state: string;
  generation: number;
  sequence: number;
  pending_inputs: number;
  created_at: string;
  updated_at: string;
}

export interface Timeline {
  thread: Thread;
  events: Array<Event>;
  next_sequence: number;
  has_more: boolean;
}

export interface Transfer {
  id: string;
  scope: Scope;
  request: TransferRequest;
  state: string;
  artifact_id: string;
  cancel_requested: boolean;
  error: string;
  wait_until: string;
  created_at: string;
}

export interface TransferRequest {
  request_id: string;
  source?: FileLocation | null;
  target?: FileLocation | null;
  artifact_id?: string;
  name?: string;
  media_type?: string;
  visibility?: string;
}

export interface User {
  id: string;
  email: string;
  email_verified: boolean;
}

export interface WorkerRequest {
  request_id: string;
  name: string;
}
