// Code generated by go run ./scripts/gen-module-schema. DO NOT EDIT.

export interface EventCursor {
  generation_id: string;
  seq: number;
  offset: number;
}

export interface GoalStatusSnapshot {
  description?: string;
  acceptance?: string;
  continuation_count?: number;
  status?: string;
  status_reason?: string;
  updated_at?: string;
}

export interface ModuleState {
  module_id: string;
  version: number;
  revision: string;
  status: string;
  value: unknown;
  error?: string;
  resources: Array<string>;
  operations: Array<string>;
}

export interface NotesSnapshot {
  content: string;
  updated_at?: string;
}

export interface ThreadModulesSnapshot {
  agent_id: string;
  thread_id: string;
  composition_revision: string;
  revision: string;
  read_only: boolean;
  observed_cursor: EventCursor;
  modules: Record<string, ModuleState>;
  ui: Array<UIContribution>;
}

export interface UIContribution {
  id: string;
  module_id: string;
  version: number;
}

export interface ModulePayloads {
  "goal": GoalStatusSnapshot;
  "notes": NotesSnapshot;
}
