// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package platform

import (
	"context"
	"fmt"
)

type Actor struct {
	UserID   string `thrift:"userID,1,required" frugal:"1,required,string" json:"userID"`
	TenantID string `thrift:"tenantID,2,required" frugal:"2,required,string" json:"tenantID"`
	AgentID  string `thrift:"agentID,3,required" frugal:"3,required,string" json:"agentID"`
}

func NewActor() *Actor {
	return &Actor{}
}

func (p *Actor) InitDefault() {
}

func (p *Actor) GetUserID() (v string) {
	return p.UserID
}

func (p *Actor) GetTenantID() (v string) {
	return p.TenantID
}

func (p *Actor) GetAgentID() (v string) {
	return p.AgentID
}
func (p *Actor) SetUserID(val string) {
	p.UserID = val
}
func (p *Actor) SetTenantID(val string) {
	p.TenantID = val
}
func (p *Actor) SetAgentID(val string) {
	p.AgentID = val
}

func (p *Actor) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Actor(%+v)", *p)
}

var fieldIDToName_Actor = map[int16]string{
	1: "userID",
	2: "tenantID",
	3: "agentID",
}

type Reply struct {
	Code string `thrift:"code,1,required" frugal:"1,required,string" json:"code"`
	Json string `thrift:"json,2,required" frugal:"2,required,string" json:"json"`
}

func NewReply() *Reply {
	return &Reply{}
}

func (p *Reply) InitDefault() {
}

func (p *Reply) GetCode() (v string) {
	return p.Code
}

func (p *Reply) GetJson() (v string) {
	return p.Json
}
func (p *Reply) SetCode(val string) {
	p.Code = val
}
func (p *Reply) SetJson(val string) {
	p.Json = val
}

func (p *Reply) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Reply(%+v)", *p)
}

var fieldIDToName_Reply = map[int16]string{
	1: "code",
	2: "json",
}

type Management interface {
	Authorize(ctx context.Context, actor *Actor, execute bool) (r *Reply, err error)

	Snapshot(ctx context.Context, scopeJSON string) (r *Reply, err error)

	ModelProfile(ctx context.Context, scopeJSON string, configJSON string) (r *Reply, err error)
}

type ManagementAuthorizeArgs struct {
	Actor   *Actor `thrift:"actor,1" frugal:"1,default,Actor" json:"actor"`
	Execute bool   `thrift:"execute,2" frugal:"2,default,bool" json:"execute"`
}

func NewManagementAuthorizeArgs() *ManagementAuthorizeArgs {
	return &ManagementAuthorizeArgs{}
}

func (p *ManagementAuthorizeArgs) InitDefault() {
}

var ManagementAuthorizeArgs_Actor_DEFAULT *Actor

func (p *ManagementAuthorizeArgs) GetActor() (v *Actor) {
	if !p.IsSetActor() {
		return ManagementAuthorizeArgs_Actor_DEFAULT
	}
	return p.Actor
}

func (p *ManagementAuthorizeArgs) GetExecute() (v bool) {
	return p.Execute
}
func (p *ManagementAuthorizeArgs) SetActor(val *Actor) {
	p.Actor = val
}
func (p *ManagementAuthorizeArgs) SetExecute(val bool) {
	p.Execute = val
}

func (p *ManagementAuthorizeArgs) IsSetActor() bool {
	return p.Actor != nil
}

func (p *ManagementAuthorizeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManagementAuthorizeArgs(%+v)", *p)
}

var fieldIDToName_ManagementAuthorizeArgs = map[int16]string{
	1: "actor",
	2: "execute",
}

type ManagementAuthorizeResult struct {
	Success *Reply `thrift:"success,0,optional" frugal:"0,optional,Reply" json:"success,omitempty"`
}

func NewManagementAuthorizeResult() *ManagementAuthorizeResult {
	return &ManagementAuthorizeResult{}
}

func (p *ManagementAuthorizeResult) InitDefault() {
}

var ManagementAuthorizeResult_Success_DEFAULT *Reply

func (p *ManagementAuthorizeResult) GetSuccess() (v *Reply) {
	if !p.IsSetSuccess() {
		return ManagementAuthorizeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ManagementAuthorizeResult) SetSuccess(x interface{}) {
	p.Success = x.(*Reply)
}

func (p *ManagementAuthorizeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ManagementAuthorizeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManagementAuthorizeResult(%+v)", *p)
}

var fieldIDToName_ManagementAuthorizeResult = map[int16]string{
	0: "success",
}

type ManagementSnapshotArgs struct {
	ScopeJSON string `thrift:"scopeJSON,1" frugal:"1,default,string" json:"scopeJSON"`
}

func NewManagementSnapshotArgs() *ManagementSnapshotArgs {
	return &ManagementSnapshotArgs{}
}

func (p *ManagementSnapshotArgs) InitDefault() {
}

func (p *ManagementSnapshotArgs) GetScopeJSON() (v string) {
	return p.ScopeJSON
}
func (p *ManagementSnapshotArgs) SetScopeJSON(val string) {
	p.ScopeJSON = val
}

func (p *ManagementSnapshotArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManagementSnapshotArgs(%+v)", *p)
}

var fieldIDToName_ManagementSnapshotArgs = map[int16]string{
	1: "scopeJSON",
}

type ManagementSnapshotResult struct {
	Success *Reply `thrift:"success,0,optional" frugal:"0,optional,Reply" json:"success,omitempty"`
}

func NewManagementSnapshotResult() *ManagementSnapshotResult {
	return &ManagementSnapshotResult{}
}

func (p *ManagementSnapshotResult) InitDefault() {
}

var ManagementSnapshotResult_Success_DEFAULT *Reply

func (p *ManagementSnapshotResult) GetSuccess() (v *Reply) {
	if !p.IsSetSuccess() {
		return ManagementSnapshotResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ManagementSnapshotResult) SetSuccess(x interface{}) {
	p.Success = x.(*Reply)
}

func (p *ManagementSnapshotResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ManagementSnapshotResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManagementSnapshotResult(%+v)", *p)
}

var fieldIDToName_ManagementSnapshotResult = map[int16]string{
	0: "success",
}

type ManagementModelProfileArgs struct {
	ScopeJSON  string `thrift:"scopeJSON,1" frugal:"1,default,string" json:"scopeJSON"`
	ConfigJSON string `thrift:"configJSON,2" frugal:"2,default,string" json:"configJSON"`
}

func NewManagementModelProfileArgs() *ManagementModelProfileArgs {
	return &ManagementModelProfileArgs{}
}

func (p *ManagementModelProfileArgs) InitDefault() {
}

func (p *ManagementModelProfileArgs) GetScopeJSON() (v string) {
	return p.ScopeJSON
}

func (p *ManagementModelProfileArgs) GetConfigJSON() (v string) {
	return p.ConfigJSON
}
func (p *ManagementModelProfileArgs) SetScopeJSON(val string) {
	p.ScopeJSON = val
}
func (p *ManagementModelProfileArgs) SetConfigJSON(val string) {
	p.ConfigJSON = val
}

func (p *ManagementModelProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManagementModelProfileArgs(%+v)", *p)
}

var fieldIDToName_ManagementModelProfileArgs = map[int16]string{
	1: "scopeJSON",
	2: "configJSON",
}

type ManagementModelProfileResult struct {
	Success *Reply `thrift:"success,0,optional" frugal:"0,optional,Reply" json:"success,omitempty"`
}

func NewManagementModelProfileResult() *ManagementModelProfileResult {
	return &ManagementModelProfileResult{}
}

func (p *ManagementModelProfileResult) InitDefault() {
}

var ManagementModelProfileResult_Success_DEFAULT *Reply

func (p *ManagementModelProfileResult) GetSuccess() (v *Reply) {
	if !p.IsSetSuccess() {
		return ManagementModelProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ManagementModelProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*Reply)
}

func (p *ManagementModelProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ManagementModelProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ManagementModelProfileResult(%+v)", *p)
}

var fieldIDToName_ManagementModelProfileResult = map[int16]string{
	0: "success",
}

type Runtime interface {
	Health(ctx context.Context) (r *Reply, err error)

	Submit(ctx context.Context, actor *Actor, requestID string, threadID string, text string) (r *Reply, err error)

	Threads(ctx context.Context, actor *Actor) (r *Reply, err error)

	Timeline(ctx context.Context, actor *Actor, threadID string, after int64, limit int32) (r *Reply, err error)

	Cancel(ctx context.Context, actor *Actor, threadID string) (r *Reply, err error)

	CreateWorker(ctx context.Context, actor *Actor, parentID string, requestID string, name string) (r *Reply, err error)
}

type RuntimeHealthArgs struct {
}

func NewRuntimeHealthArgs() *RuntimeHealthArgs {
	return &RuntimeHealthArgs{}
}

func (p *RuntimeHealthArgs) InitDefault() {
}

func (p *RuntimeHealthArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeHealthArgs(%+v)", *p)
}

var fieldIDToName_RuntimeHealthArgs = map[int16]string{}

type RuntimeHealthResult struct {
	Success *Reply `thrift:"success,0,optional" frugal:"0,optional,Reply" json:"success,omitempty"`
}

func NewRuntimeHealthResult() *RuntimeHealthResult {
	return &RuntimeHealthResult{}
}

func (p *RuntimeHealthResult) InitDefault() {
}

var RuntimeHealthResult_Success_DEFAULT *Reply

func (p *RuntimeHealthResult) GetSuccess() (v *Reply) {
	if !p.IsSetSuccess() {
		return RuntimeHealthResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RuntimeHealthResult) SetSuccess(x interface{}) {
	p.Success = x.(*Reply)
}

func (p *RuntimeHealthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RuntimeHealthResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeHealthResult(%+v)", *p)
}

var fieldIDToName_RuntimeHealthResult = map[int16]string{
	0: "success",
}

type RuntimeSubmitArgs struct {
	Actor     *Actor `thrift:"actor,1" frugal:"1,default,Actor" json:"actor"`
	RequestID string `thrift:"requestID,2" frugal:"2,default,string" json:"requestID"`
	ThreadID  string `thrift:"threadID,3" frugal:"3,default,string" json:"threadID"`
	Text      string `thrift:"text,4" frugal:"4,default,string" json:"text"`
}

func NewRuntimeSubmitArgs() *RuntimeSubmitArgs {
	return &RuntimeSubmitArgs{}
}

func (p *RuntimeSubmitArgs) InitDefault() {
}

var RuntimeSubmitArgs_Actor_DEFAULT *Actor

func (p *RuntimeSubmitArgs) GetActor() (v *Actor) {
	if !p.IsSetActor() {
		return RuntimeSubmitArgs_Actor_DEFAULT
	}
	return p.Actor
}

func (p *RuntimeSubmitArgs) GetRequestID() (v string) {
	return p.RequestID
}

func (p *RuntimeSubmitArgs) GetThreadID() (v string) {
	return p.ThreadID
}

func (p *RuntimeSubmitArgs) GetText() (v string) {
	return p.Text
}
func (p *RuntimeSubmitArgs) SetActor(val *Actor) {
	p.Actor = val
}
func (p *RuntimeSubmitArgs) SetRequestID(val string) {
	p.RequestID = val
}
func (p *RuntimeSubmitArgs) SetThreadID(val string) {
	p.ThreadID = val
}
func (p *RuntimeSubmitArgs) SetText(val string) {
	p.Text = val
}

func (p *RuntimeSubmitArgs) IsSetActor() bool {
	return p.Actor != nil
}

func (p *RuntimeSubmitArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeSubmitArgs(%+v)", *p)
}

var fieldIDToName_RuntimeSubmitArgs = map[int16]string{
	1: "actor",
	2: "requestID",
	3: "threadID",
	4: "text",
}

type RuntimeSubmitResult struct {
	Success *Reply `thrift:"success,0,optional" frugal:"0,optional,Reply" json:"success,omitempty"`
}

func NewRuntimeSubmitResult() *RuntimeSubmitResult {
	return &RuntimeSubmitResult{}
}

func (p *RuntimeSubmitResult) InitDefault() {
}

var RuntimeSubmitResult_Success_DEFAULT *Reply

func (p *RuntimeSubmitResult) GetSuccess() (v *Reply) {
	if !p.IsSetSuccess() {
		return RuntimeSubmitResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RuntimeSubmitResult) SetSuccess(x interface{}) {
	p.Success = x.(*Reply)
}

func (p *RuntimeSubmitResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RuntimeSubmitResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeSubmitResult(%+v)", *p)
}

var fieldIDToName_RuntimeSubmitResult = map[int16]string{
	0: "success",
}

type RuntimeThreadsArgs struct {
	Actor *Actor `thrift:"actor,1" frugal:"1,default,Actor" json:"actor"`
}

func NewRuntimeThreadsArgs() *RuntimeThreadsArgs {
	return &RuntimeThreadsArgs{}
}

func (p *RuntimeThreadsArgs) InitDefault() {
}

var RuntimeThreadsArgs_Actor_DEFAULT *Actor

func (p *RuntimeThreadsArgs) GetActor() (v *Actor) {
	if !p.IsSetActor() {
		return RuntimeThreadsArgs_Actor_DEFAULT
	}
	return p.Actor
}
func (p *RuntimeThreadsArgs) SetActor(val *Actor) {
	p.Actor = val
}

func (p *RuntimeThreadsArgs) IsSetActor() bool {
	return p.Actor != nil
}

func (p *RuntimeThreadsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeThreadsArgs(%+v)", *p)
}

var fieldIDToName_RuntimeThreadsArgs = map[int16]string{
	1: "actor",
}

type RuntimeThreadsResult struct {
	Success *Reply `thrift:"success,0,optional" frugal:"0,optional,Reply" json:"success,omitempty"`
}

func NewRuntimeThreadsResult() *RuntimeThreadsResult {
	return &RuntimeThreadsResult{}
}

func (p *RuntimeThreadsResult) InitDefault() {
}

var RuntimeThreadsResult_Success_DEFAULT *Reply

func (p *RuntimeThreadsResult) GetSuccess() (v *Reply) {
	if !p.IsSetSuccess() {
		return RuntimeThreadsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RuntimeThreadsResult) SetSuccess(x interface{}) {
	p.Success = x.(*Reply)
}

func (p *RuntimeThreadsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RuntimeThreadsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeThreadsResult(%+v)", *p)
}

var fieldIDToName_RuntimeThreadsResult = map[int16]string{
	0: "success",
}

type RuntimeTimelineArgs struct {
	Actor    *Actor `thrift:"actor,1" frugal:"1,default,Actor" json:"actor"`
	ThreadID string `thrift:"threadID,2" frugal:"2,default,string" json:"threadID"`
	After    int64  `thrift:"after,3" frugal:"3,default,i64" json:"after"`
	Limit    int32  `thrift:"limit,4" frugal:"4,default,i32" json:"limit"`
}

func NewRuntimeTimelineArgs() *RuntimeTimelineArgs {
	return &RuntimeTimelineArgs{}
}

func (p *RuntimeTimelineArgs) InitDefault() {
}

var RuntimeTimelineArgs_Actor_DEFAULT *Actor

func (p *RuntimeTimelineArgs) GetActor() (v *Actor) {
	if !p.IsSetActor() {
		return RuntimeTimelineArgs_Actor_DEFAULT
	}
	return p.Actor
}

func (p *RuntimeTimelineArgs) GetThreadID() (v string) {
	return p.ThreadID
}

func (p *RuntimeTimelineArgs) GetAfter() (v int64) {
	return p.After
}

func (p *RuntimeTimelineArgs) GetLimit() (v int32) {
	return p.Limit
}
func (p *RuntimeTimelineArgs) SetActor(val *Actor) {
	p.Actor = val
}
func (p *RuntimeTimelineArgs) SetThreadID(val string) {
	p.ThreadID = val
}
func (p *RuntimeTimelineArgs) SetAfter(val int64) {
	p.After = val
}
func (p *RuntimeTimelineArgs) SetLimit(val int32) {
	p.Limit = val
}

func (p *RuntimeTimelineArgs) IsSetActor() bool {
	return p.Actor != nil
}

func (p *RuntimeTimelineArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeTimelineArgs(%+v)", *p)
}

var fieldIDToName_RuntimeTimelineArgs = map[int16]string{
	1: "actor",
	2: "threadID",
	3: "after",
	4: "limit",
}

type RuntimeTimelineResult struct {
	Success *Reply `thrift:"success,0,optional" frugal:"0,optional,Reply" json:"success,omitempty"`
}

func NewRuntimeTimelineResult() *RuntimeTimelineResult {
	return &RuntimeTimelineResult{}
}

func (p *RuntimeTimelineResult) InitDefault() {
}

var RuntimeTimelineResult_Success_DEFAULT *Reply

func (p *RuntimeTimelineResult) GetSuccess() (v *Reply) {
	if !p.IsSetSuccess() {
		return RuntimeTimelineResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RuntimeTimelineResult) SetSuccess(x interface{}) {
	p.Success = x.(*Reply)
}

func (p *RuntimeTimelineResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RuntimeTimelineResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeTimelineResult(%+v)", *p)
}

var fieldIDToName_RuntimeTimelineResult = map[int16]string{
	0: "success",
}

type RuntimeCancelArgs struct {
	Actor    *Actor `thrift:"actor,1" frugal:"1,default,Actor" json:"actor"`
	ThreadID string `thrift:"threadID,2" frugal:"2,default,string" json:"threadID"`
}

func NewRuntimeCancelArgs() *RuntimeCancelArgs {
	return &RuntimeCancelArgs{}
}

func (p *RuntimeCancelArgs) InitDefault() {
}

var RuntimeCancelArgs_Actor_DEFAULT *Actor

func (p *RuntimeCancelArgs) GetActor() (v *Actor) {
	if !p.IsSetActor() {
		return RuntimeCancelArgs_Actor_DEFAULT
	}
	return p.Actor
}

func (p *RuntimeCancelArgs) GetThreadID() (v string) {
	return p.ThreadID
}
func (p *RuntimeCancelArgs) SetActor(val *Actor) {
	p.Actor = val
}
func (p *RuntimeCancelArgs) SetThreadID(val string) {
	p.ThreadID = val
}

func (p *RuntimeCancelArgs) IsSetActor() bool {
	return p.Actor != nil
}

func (p *RuntimeCancelArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeCancelArgs(%+v)", *p)
}

var fieldIDToName_RuntimeCancelArgs = map[int16]string{
	1: "actor",
	2: "threadID",
}

type RuntimeCancelResult struct {
	Success *Reply `thrift:"success,0,optional" frugal:"0,optional,Reply" json:"success,omitempty"`
}

func NewRuntimeCancelResult() *RuntimeCancelResult {
	return &RuntimeCancelResult{}
}

func (p *RuntimeCancelResult) InitDefault() {
}

var RuntimeCancelResult_Success_DEFAULT *Reply

func (p *RuntimeCancelResult) GetSuccess() (v *Reply) {
	if !p.IsSetSuccess() {
		return RuntimeCancelResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RuntimeCancelResult) SetSuccess(x interface{}) {
	p.Success = x.(*Reply)
}

func (p *RuntimeCancelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RuntimeCancelResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeCancelResult(%+v)", *p)
}

var fieldIDToName_RuntimeCancelResult = map[int16]string{
	0: "success",
}

type RuntimeCreateWorkerArgs struct {
	Actor     *Actor `thrift:"actor,1" frugal:"1,default,Actor" json:"actor"`
	ParentID  string `thrift:"parentID,2" frugal:"2,default,string" json:"parentID"`
	RequestID string `thrift:"requestID,3" frugal:"3,default,string" json:"requestID"`
	Name      string `thrift:"name,4" frugal:"4,default,string" json:"name"`
}

func NewRuntimeCreateWorkerArgs() *RuntimeCreateWorkerArgs {
	return &RuntimeCreateWorkerArgs{}
}

func (p *RuntimeCreateWorkerArgs) InitDefault() {
}

var RuntimeCreateWorkerArgs_Actor_DEFAULT *Actor

func (p *RuntimeCreateWorkerArgs) GetActor() (v *Actor) {
	if !p.IsSetActor() {
		return RuntimeCreateWorkerArgs_Actor_DEFAULT
	}
	return p.Actor
}

func (p *RuntimeCreateWorkerArgs) GetParentID() (v string) {
	return p.ParentID
}

func (p *RuntimeCreateWorkerArgs) GetRequestID() (v string) {
	return p.RequestID
}

func (p *RuntimeCreateWorkerArgs) GetName() (v string) {
	return p.Name
}
func (p *RuntimeCreateWorkerArgs) SetActor(val *Actor) {
	p.Actor = val
}
func (p *RuntimeCreateWorkerArgs) SetParentID(val string) {
	p.ParentID = val
}
func (p *RuntimeCreateWorkerArgs) SetRequestID(val string) {
	p.RequestID = val
}
func (p *RuntimeCreateWorkerArgs) SetName(val string) {
	p.Name = val
}

func (p *RuntimeCreateWorkerArgs) IsSetActor() bool {
	return p.Actor != nil
}

func (p *RuntimeCreateWorkerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeCreateWorkerArgs(%+v)", *p)
}

var fieldIDToName_RuntimeCreateWorkerArgs = map[int16]string{
	1: "actor",
	2: "parentID",
	3: "requestID",
	4: "name",
}

type RuntimeCreateWorkerResult struct {
	Success *Reply `thrift:"success,0,optional" frugal:"0,optional,Reply" json:"success,omitempty"`
}

func NewRuntimeCreateWorkerResult() *RuntimeCreateWorkerResult {
	return &RuntimeCreateWorkerResult{}
}

func (p *RuntimeCreateWorkerResult) InitDefault() {
}

var RuntimeCreateWorkerResult_Success_DEFAULT *Reply

func (p *RuntimeCreateWorkerResult) GetSuccess() (v *Reply) {
	if !p.IsSetSuccess() {
		return RuntimeCreateWorkerResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RuntimeCreateWorkerResult) SetSuccess(x interface{}) {
	p.Success = x.(*Reply)
}

func (p *RuntimeCreateWorkerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RuntimeCreateWorkerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RuntimeCreateWorkerResult(%+v)", *p)
}

var fieldIDToName_RuntimeCreateWorkerResult = map[int16]string{
	0: "success",
}
